export type DailyInspirationVerseReference = {
  book: string;
  chapter: number;
  verse: number;
};

/** Hand-picked and vetted uplifting verses for the home "Verse for today" card (~3-year rotation). */
export const CURATED_DAILY_INSPIRATION_VERSE_REFERENCES: DailyInspirationVerseReference[] = [
  { book: 'Psalms', chapter: 23, verse: 1 },
  { book: 'Psalms', chapter: 23, verse: 4 },
  { book: 'Psalms', chapter: 23, verse: 6 },
  { book: 'Psalms', chapter: 27, verse: 1 },
  { book: 'Psalms', chapter: 27, verse: 14 },
  { book: 'Psalms', chapter: 28, verse: 7 },
  { book: 'Psalms', chapter: 29, verse: 11 },
  { book: 'Psalms', chapter: 30, verse: 5 },
  { book: 'Psalms', chapter: 31, verse: 24 },
  { book: 'Psalms', chapter: 32, verse: 8 },
  { book: 'Psalms', chapter: 34, verse: 4 },
  { book: 'Psalms', chapter: 34, verse: 8 },
  { book: 'Psalms', chapter: 34, verse: 18 },
  { book: 'Psalms', chapter: 37, verse: 4 },
  { book: 'Psalms', chapter: 37, verse: 5 },
  { book: 'Psalms', chapter: 37, verse: 39 },
  { book: 'Psalms', chapter: 46, verse: 1 },
  { book: 'Psalms', chapter: 46, verse: 10 },
  { book: 'Psalms', chapter: 55, verse: 22 },
  { book: 'Psalms', chapter: 56, verse: 3 },
  { book: 'Psalms', chapter: 62, verse: 1 },
  { book: 'Psalms', chapter: 62, verse: 5 },
  { book: 'Psalms', chapter: 63, verse: 3 },
  { book: 'Psalms', chapter: 73, verse: 26 },
  { book: 'Psalms', chapter: 84, verse: 11 },
  { book: 'Psalms', chapter: 86, verse: 15 },
  { book: 'Psalms', chapter: 91, verse: 1 },
  { book: 'Psalms', chapter: 91, verse: 2 },
  { book: 'Psalms', chapter: 91, verse: 4 },
  { book: 'Psalms', chapter: 94, verse: 19 },
  { book: 'Psalms', chapter: 100, verse: 4 },
  { book: 'Psalms', chapter: 100, verse: 5 },
  { book: 'Psalms', chapter: 103, verse: 1 },
  { book: 'Psalms', chapter: 103, verse: 8 },
  { book: 'Psalms', chapter: 103, verse: 12 },
  { book: 'Psalms', chapter: 107, verse: 1 },
  { book: 'Psalms', chapter: 118, verse: 6 },
  { book: 'Psalms', chapter: 118, verse: 24 },
  { book: 'Psalms', chapter: 119, verse: 105 },
  { book: 'Psalms', chapter: 121, verse: 1 },
  { book: 'Psalms', chapter: 121, verse: 2 },
  { book: 'Psalms', chapter: 126, verse: 5 },
  { book: 'Psalms', chapter: 136, verse: 1 },
  { book: 'Psalms', chapter: 138, verse: 7 },
  { book: 'Psalms', chapter: 139, verse: 14 },
  { book: 'Psalms', chapter: 145, verse: 8 },
  { book: 'Psalms', chapter: 145, verse: 18 },
  { book: 'Psalms', chapter: 147, verse: 3 },
  { book: 'Psalms', chapter: 16, verse: 11 },
  { book: 'Psalms', chapter: 18, verse: 2 },
  { book: 'Psalms', chapter: 19, verse: 14 },
  { book: 'Psalms', chapter: 4, verse: 8 },
  { book: 'Jeremiah', chapter: 29, verse: 11 },
  { book: 'Jeremiah', chapter: 31, verse: 3 },
  { book: 'Joshua', chapter: 1, verse: 9 },
  { book: 'Deuteronomy', chapter: 31, verse: 6 },
  { book: 'Lamentations', chapter: 3, verse: 22 },
  { book: 'Lamentations', chapter: 3, verse: 23 },
  { book: 'Micah', chapter: 6, verse: 8 },
  { book: 'Nehemiah', chapter: 8, verse: 10 },
  { book: 'Proverbs', chapter: 3, verse: 5 },
  { book: 'Proverbs', chapter: 3, verse: 6 },
  { book: 'Proverbs', chapter: 3, verse: 13 },
  { book: 'Proverbs', chapter: 4, verse: 23 },
  { book: 'Proverbs', chapter: 10, verse: 12 },
  { book: 'Proverbs', chapter: 11, verse: 25 },
  { book: 'Proverbs', chapter: 16, verse: 3 },
  { book: 'Proverbs', chapter: 16, verse: 9 },
  { book: 'Proverbs', chapter: 16, verse: 24 },
  { book: 'Proverbs', chapter: 17, verse: 17 },
  { book: 'Proverbs', chapter: 18, verse: 10 },
  { book: 'Proverbs', chapter: 19, verse: 21 },
  { book: 'Proverbs', chapter: 22, verse: 4 },
  { book: 'Proverbs', chapter: 27, verse: 17 },
  { book: 'Proverbs', chapter: 31, verse: 25 },
  { book: 'Isaiah', chapter: 26, verse: 3 },
  { book: 'Isaiah', chapter: 40, verse: 8 },
  { book: 'Isaiah', chapter: 40, verse: 29 },
  { book: 'Isaiah', chapter: 40, verse: 31 },
  { book: 'Isaiah', chapter: 41, verse: 10 },
  { book: 'Isaiah', chapter: 41, verse: 13 },
  { book: 'Isaiah', chapter: 43, verse: 2 },
  { book: 'Isaiah', chapter: 46, verse: 4 },
  { book: 'Isaiah', chapter: 49, verse: 16 },
  { book: 'Isaiah', chapter: 55, verse: 6 },
  { book: 'Isaiah', chapter: 55, verse: 8 },
  { book: 'Isaiah', chapter: 55, verse: 11 },
  { book: 'Isaiah', chapter: 58, verse: 11 },
  { book: 'Isaiah', chapter: 12, verse: 2 },
  { book: 'Isaiah', chapter: 32, verse: 17 },
  { book: 'Matthew', chapter: 5, verse: 4 },
  { book: 'Matthew', chapter: 5, verse: 9 },
  { book: 'Matthew', chapter: 5, verse: 14 },
  { book: 'Matthew', chapter: 5, verse: 16 },
  { book: 'Matthew', chapter: 6, verse: 33 },
  { book: 'Matthew', chapter: 6, verse: 34 },
  { book: 'Matthew', chapter: 7, verse: 7 },
  { book: 'Matthew', chapter: 7, verse: 12 },
  { book: 'Matthew', chapter: 11, verse: 28 },
  { book: 'Matthew', chapter: 11, verse: 29 },
  { book: 'Matthew', chapter: 17, verse: 20 },
  { book: 'Matthew', chapter: 19, verse: 26 },
  { book: 'Matthew', chapter: 22, verse: 37 },
  { book: 'Matthew', chapter: 28, verse: 20 },
  { book: 'Mark', chapter: 9, verse: 23 },
  { book: 'Mark', chapter: 10, verse: 27 },
  { book: 'Mark', chapter: 11, verse: 24 },
  { book: 'Mark', chapter: 12, verse: 30 },
  { book: 'Luke', chapter: 1, verse: 37 },
  { book: 'Luke', chapter: 6, verse: 31 },
  { book: 'Luke', chapter: 6, verse: 38 },
  { book: 'Luke', chapter: 11, verse: 9 },
  { book: 'Luke', chapter: 12, verse: 32 },
  { book: 'Luke', chapter: 18, verse: 27 },
  { book: 'John', chapter: 1, verse: 12 },
  { book: 'John', chapter: 3, verse: 16 },
  { book: 'John', chapter: 3, verse: 17 },
  { book: 'John', chapter: 4, verse: 14 },
  { book: 'John', chapter: 6, verse: 35 },
  { book: 'John', chapter: 8, verse: 12 },
  { book: 'John', chapter: 8, verse: 32 },
  { book: 'John', chapter: 10, verse: 10 },
  { book: 'John', chapter: 10, verse: 11 },
  { book: 'John', chapter: 11, verse: 25 },
  { book: 'John', chapter: 14, verse: 1 },
  { book: 'John', chapter: 14, verse: 6 },
  { book: 'John', chapter: 14, verse: 27 },
  { book: 'John', chapter: 15, verse: 5 },
  { book: 'John', chapter: 15, verse: 13 },
  { book: 'John', chapter: 16, verse: 33 },
  { book: 'Romans', chapter: 5, verse: 8 },
  { book: 'Romans', chapter: 8, verse: 28 },
  { book: 'Romans', chapter: 8, verse: 31 },
  { book: 'Romans', chapter: 8, verse: 38 },
  { book: 'Romans', chapter: 8, verse: 39 },
  { book: 'Romans', chapter: 12, verse: 2 },
  { book: 'Romans', chapter: 12, verse: 12 },
  { book: 'Romans', chapter: 12, verse: 21 },
  { book: 'Romans', chapter: 15, verse: 13 },
  { book: '1 Corinthians', chapter: 10, verse: 13 },
  { book: '1 Corinthians', chapter: 13, verse: 4 },
  { book: '1 Corinthians', chapter: 13, verse: 13 },
  { book: '1 Corinthians', chapter: 15, verse: 57 },
  { book: '2 Corinthians', chapter: 4, verse: 16 },
  { book: '2 Corinthians', chapter: 4, verse: 17 },
  { book: '2 Corinthians', chapter: 5, verse: 7 },
  { book: '2 Corinthians', chapter: 5, verse: 17 },
  { book: '2 Corinthians', chapter: 12, verse: 9 },
  { book: 'Galatians', chapter: 2, verse: 20 },
  { book: 'Galatians', chapter: 5, verse: 22 },
  { book: 'Galatians', chapter: 5, verse: 23 },
  { book: 'Galatians', chapter: 6, verse: 9 },
  { book: 'Ephesians', chapter: 2, verse: 8 },
  { book: 'Ephesians', chapter: 3, verse: 20 },
  { book: 'Ephesians', chapter: 4, verse: 2 },
  { book: 'Ephesians', chapter: 4, verse: 32 },
  { book: 'Ephesians', chapter: 6, verse: 10 },
  { book: 'Philippians', chapter: 1, verse: 6 },
  { book: 'Philippians', chapter: 2, verse: 3 },
  { book: 'Philippians', chapter: 2, verse: 4 },
  { book: 'Philippians', chapter: 3, verse: 13 },
  { book: 'Philippians', chapter: 3, verse: 14 },
  { book: 'Philippians', chapter: 4, verse: 4 },
  { book: 'Philippians', chapter: 4, verse: 6 },
  { book: 'Philippians', chapter: 4, verse: 7 },
  { book: 'Philippians', chapter: 4, verse: 8 },
  { book: 'Philippians', chapter: 4, verse: 13 },
  { book: 'Philippians', chapter: 4, verse: 19 },
  { book: 'Colossians', chapter: 3, verse: 12 },
  { book: 'Colossians', chapter: 3, verse: 14 },
  { book: 'Colossians', chapter: 3, verse: 15 },
  { book: 'Colossians', chapter: 3, verse: 17 },
  { book: 'Colossians', chapter: 3, verse: 23 },
  { book: '1 Thessalonians', chapter: 5, verse: 16 },
  { book: '1 Thessalonians', chapter: 5, verse: 17 },
  { book: '1 Thessalonians', chapter: 5, verse: 18 },
  { book: '1 Thessalonians', chapter: 5, verse: 24 },
  { book: '2 Thessalonians', chapter: 3, verse: 3 },
  { book: '1 Timothy', chapter: 4, verse: 12 },
  { book: '2 Timothy', chapter: 1, verse: 7 },
  { book: '2 Timothy', chapter: 1, verse: 9 },
  { book: '2 Timothy', chapter: 4, verse: 7 },
  { book: 'Hebrews', chapter: 4, verse: 16 },
  { book: 'Hebrews', chapter: 10, verse: 23 },
  { book: 'Hebrews', chapter: 10, verse: 24 },
  { book: 'Hebrews', chapter: 11, verse: 1 },
  { book: 'Hebrews', chapter: 11, verse: 6 },
  { book: 'Hebrews', chapter: 13, verse: 5 },
  { book: 'Hebrews', chapter: 13, verse: 8 },
  { book: 'James', chapter: 1, verse: 2 },
  { book: 'James', chapter: 1, verse: 5 },
  { book: 'James', chapter: 1, verse: 17 },
  { book: 'James', chapter: 4, verse: 8 },
  { book: '1 Peter', chapter: 1, verse: 3 },
  { book: '1 Peter', chapter: 3, verse: 15 },
  { book: '1 Peter', chapter: 5, verse: 7 },
  { book: '1 Peter', chapter: 5, verse: 10 },
  { book: '2 Peter', chapter: 1, verse: 3 },
  { book: '1 John', chapter: 3, verse: 1 },
  { book: '1 John', chapter: 3, verse: 18 },
  { book: '1 John', chapter: 4, verse: 7 },
  { book: '1 John', chapter: 4, verse: 8 },
  { book: '1 John', chapter: 4, verse: 16 },
  { book: '1 John', chapter: 4, verse: 19 },
  { book: '2 Thessalonians', chapter: 2, verse: 16 },
  { book: '2 Corinthians', chapter: 1, verse: 3 },
  { book: 'Ephesians', chapter: 1, verse: 3 },
  { book: 'Psalms', chapter: 30, verse: 12 },
  { book: '1 Thessalonians', chapter: 1, verse: 3 },
  { book: '2 Corinthians', chapter: 13, verse: 14 },
  { book: 'Acts', chapter: 11, verse: 23 },
  { book: 'Ephesians', chapter: 1, verse: 17 },
  { book: 'Ephesians', chapter: 6, verse: 23 },
  { book: 'Titus', chapter: 2, verse: 13 },
  { book: '1 Corinthians', chapter: 1, verse: 3 },
  { book: '1 John', chapter: 5, verse: 1 },
  { book: '1 Peter', chapter: 4, verse: 14 },
  { book: '1 Thessalonians', chapter: 1, verse: 1 },
  { book: '2 Corinthians', chapter: 1, verse: 2 },
  { book: '2 Corinthians', chapter: 11, verse: 31 },
  { book: '2 Thessalonians', chapter: 1, verse: 2 },
  { book: 'Ephesians', chapter: 1, verse: 2 },
  { book: 'Galatians', chapter: 1, verse: 3 },
  { book: 'James', chapter: 5, verse: 15 },
  { book: 'Philippians', chapter: 1, verse: 11 },
  { book: 'Philippians', chapter: 1, verse: 2 },
  { book: 'Philippians', chapter: 2, verse: 1 },
  { book: 'Psalms', chapter: 138, verse: 1 },
  { book: 'Romans', chapter: 1, verse: 25 },
  { book: 'Romans', chapter: 5, verse: 5 },
  { book: '1 Corinthians', chapter: 1, verse: 7 },
  { book: '1 Corinthians', chapter: 1, verse: 9 },
  { book: '1 Thessalonians', chapter: 3, verse: 2 },
  { book: '1 Thessalonians', chapter: 5, verse: 23 },
  { book: '1 Timothy', chapter: 1, verse: 12 },
  { book: '1 Timothy', chapter: 1, verse: 14 },
  { book: '1 Timothy', chapter: 6, verse: 13 },
  { book: '2 Peter', chapter: 3, verse: 15 },
  { book: '2 Peter', chapter: 3, verse: 18 },
  { book: 'Acts', chapter: 11, verse: 17 },
  { book: 'Acts', chapter: 13, verse: 34 },
  { book: 'Ephesians', chapter: 1, verse: 13 },
  { book: 'Ephesians', chapter: 5, verse: 20 },
  { book: 'Galatians', chapter: 3, verse: 14 },
  { book: 'Galatians', chapter: 3, verse: 22 },
  { book: 'Isaiah', chapter: 52, verse: 9 },
  { book: 'Isaiah', chapter: 65, verse: 18 },
  { book: 'Philippians', chapter: 2, verse: 11 },
  { book: 'Philippians', chapter: 3, verse: 3 },
  { book: 'Psalms', chapter: 104, verse: 33 },
  { book: 'Psalms', chapter: 111, verse: 10 },
  { book: 'Psalms', chapter: 118, verse: 1 },
  { book: 'Psalms', chapter: 118, verse: 29 },
  { book: 'Psalms', chapter: 133, verse: 3 },
  { book: 'Psalms', chapter: 143, verse: 1 },
  { book: 'Psalms', chapter: 145, verse: 21 },
  { book: 'Psalms', chapter: 146, verse: 2 },
  { book: 'Psalms', chapter: 146, verse: 5 },
  { book: 'Psalms', chapter: 147, verse: 1 },
  { book: 'Psalms', chapter: 32, verse: 11 },
  { book: 'Psalms', chapter: 37, verse: 3 },
  { book: 'Psalms', chapter: 40, verse: 16 },
  { book: 'Psalms', chapter: 48, verse: 1 },
  { book: 'Psalms', chapter: 65, verse: 4 },
  { book: 'Psalms', chapter: 86, verse: 12 },
  { book: 'Psalms', chapter: 97, verse: 12 },
  { book: 'Romans', chapter: 10, verse: 9 },
  { book: 'Romans', chapter: 14, verse: 17 },
  { book: 'Romans', chapter: 15, verse: 30 },
  { book: 'Romans', chapter: 16, verse: 20 },
  { book: 'Romans', chapter: 3, verse: 22 },
  { book: 'Romans', chapter: 5, verse: 1 },
  { book: 'Romans', chapter: 5, verse: 2 },
  { book: 'Romans', chapter: 7, verse: 25 },
  { book: 'Titus', chapter: 3, verse: 5 },
  { book: '1 Corinthians', chapter: 1, verse: 30 },
  { book: '1 Corinthians', chapter: 1, verse: 4 },
  { book: '1 Corinthians', chapter: 4, verse: 17 },
  { book: '1 John', chapter: 1, verse: 9 },
  { book: '1 John', chapter: 5, verse: 4 },
  { book: '1 Peter', chapter: 1, verse: 13 },
  { book: '1 Peter', chapter: 4, verse: 19 },
  { book: '1 Thessalonians', chapter: 3, verse: 13 },
  { book: '1 Timothy', chapter: 1, verse: 1 },
  { book: '1 Timothy', chapter: 1, verse: 16 },
  { book: '1 Timothy', chapter: 1, verse: 17 },
  { book: '2 Corinthians', chapter: 4, verse: 4 },
  { book: '2 Corinthians', chapter: 6, verse: 6 },
  { book: '2 Corinthians', chapter: 9, verse: 14 },
  { book: '2 Peter', chapter: 1, verse: 11 },
  { book: '2 Peter', chapter: 1, verse: 2 },
  { book: '2 Thessalonians', chapter: 1, verse: 1 },
  { book: '2 Thessalonians', chapter: 1, verse: 12 },
  { book: '2 Thessalonians', chapter: 2, verse: 13 },
  { book: '2 Thessalonians', chapter: 2, verse: 17 },
  { book: '2 Thessalonians', chapter: 3, verse: 5 },
  { book: '2 Timothy', chapter: 1, verse: 1 },
  { book: '2 Timothy', chapter: 1, verse: 14 },
  { book: '2 Timothy', chapter: 2, verse: 10 },
  { book: '2 Timothy', chapter: 3, verse: 15 },
  { book: 'Acts', chapter: 11, verse: 24 },
  { book: 'Acts', chapter: 13, verse: 48 },
  { book: 'Acts', chapter: 14, verse: 17 },
  { book: 'Acts', chapter: 15, verse: 11 },
  { book: 'Acts', chapter: 2, verse: 26 },
  { book: 'Acts', chapter: 2, verse: 33 },
  { book: 'Acts', chapter: 2, verse: 38 },
  { book: 'Acts', chapter: 2, verse: 47 },
  { book: 'Acts', chapter: 20, verse: 21 },
  { book: 'Acts', chapter: 20, verse: 35 },
  { book: 'Acts', chapter: 7, verse: 55 },
  { book: 'Acts', chapter: 9, verse: 31 },
  { book: 'Colossians', chapter: 1, verse: 3 },
  { book: 'Colossians', chapter: 2, verse: 5 },
  { book: 'Colossians', chapter: 3, verse: 16 },
  { book: 'Ephesians', chapter: 1, verse: 1 },
  { book: 'Ephesians', chapter: 1, verse: 12 },
  { book: 'Ephesians', chapter: 2, verse: 10 },
  { book: 'Ephesians', chapter: 3, verse: 17 },
  { book: 'Ephesians', chapter: 5, verse: 9 },
  { book: 'Ephesians', chapter: 6, verse: 24 },
  { book: 'Galatians', chapter: 5, verse: 5 },
  { book: 'Galatians', chapter: 5, verse: 6 },
  { book: 'Galatians', chapter: 6, verse: 18 },
  { book: 'Hebrews', chapter: 3, verse: 6 },
  { book: 'Isaiah', chapter: 12, verse: 1 },
  { book: 'Isaiah', chapter: 26, verse: 4 },
  { book: 'Isaiah', chapter: 30, verse: 18 },
  { book: 'Isaiah', chapter: 35, verse: 2 },
  { book: 'Isaiah', chapter: 43, verse: 3 },
  { book: 'Isaiah', chapter: 61, verse: 8 },
  { book: 'Isaiah', chapter: 9, verse: 6 },
  { book: 'James', chapter: 3, verse: 17 },
  { book: 'Jeremiah', chapter: 32, verse: 41 },
  { book: 'Jeremiah', chapter: 33, verse: 16 },
  { book: 'John', chapter: 1, verse: 14 },
  { book: 'John', chapter: 1, verse: 17 },
  { book: 'John', chapter: 17, verse: 3 },
  { book: 'John', chapter: 20, verse: 31 },
  { book: 'John', chapter: 4, verse: 21 },
  { book: 'Luke', chapter: 1, verse: 68 },
  { book: 'Luke', chapter: 19, verse: 38 },
  { book: 'Luke', chapter: 4, verse: 8 },
  { book: 'Mark', chapter: 14, verse: 11 },
  { book: 'Matthew', chapter: 4, verse: 10 },
  { book: 'Matthew', chapter: 9, verse: 2 },
  { book: 'Philippians', chapter: 3, verse: 20 },
  { book: 'Philippians', chapter: 4, verse: 23 },
  { book: 'Proverbs', chapter: 12, verse: 22 },
  { book: 'Proverbs', chapter: 3, verse: 12 },
  { book: 'Psalms', chapter: 112, verse: 1 },
  { book: 'Psalms', chapter: 112, verse: 9 },
  { book: 'Psalms', chapter: 116, verse: 6 },
  { book: 'Psalms', chapter: 125, verse: 1 },
  { book: 'Psalms', chapter: 136, verse: 2 },
  { book: 'Psalms', chapter: 136, verse: 26 },
  { book: 'Psalms', chapter: 136, verse: 3 },
  { book: 'Psalms', chapter: 145, verse: 13 },
  { book: 'Psalms', chapter: 145, verse: 7 },
  { book: 'Psalms', chapter: 149, verse: 1 },
  { book: 'Psalms', chapter: 16, verse: 9 },
  { book: 'Psalms', chapter: 18, verse: 46 },
  { book: 'Psalms', chapter: 24, verse: 5 },
  { book: 'Psalms', chapter: 25, verse: 5 },
  { book: 'Psalms', chapter: 30, verse: 4 },
  { book: 'Psalms', chapter: 33, verse: 1 },
  { book: 'Psalms', chapter: 40, verse: 3 },
  { book: 'Psalms', chapter: 46, verse: 4 },
  { book: 'Psalms', chapter: 62, verse: 7 },
  { book: 'Psalms', chapter: 73, verse: 28 },
  { book: 'Psalms', chapter: 9, verse: 11 },
  { book: 'Psalms', chapter: 9, verse: 2 },
  { book: 'Psalms', chapter: 92, verse: 1 },
  { book: 'Psalms', chapter: 98, verse: 3 },
  { book: 'Psalms', chapter: 98, verse: 4 },
  { book: 'Romans', chapter: 1, verse: 4 },
  { book: 'Romans', chapter: 15, verse: 6 },
  { book: 'Romans', chapter: 15, verse: 9 },
  { book: 'Romans', chapter: 4, verse: 20 },
  { book: 'Romans', chapter: 5, verse: 11 },
  { book: 'Romans', chapter: 9, verse: 5 },
  { book: 'Titus', chapter: 1, verse: 1 },
  { book: 'Titus', chapter: 1, verse: 2 },
  { book: '1 Corinthians', chapter: 1, verse: 8 },
  { book: '1 Corinthians', chapter: 14, verse: 16 },
  { book: '1 Corinthians', chapter: 14, verse: 3 },
  { book: '1 Corinthians', chapter: 2, verse: 13 },
  { book: '1 Corinthians', chapter: 2, verse: 5 },
  { book: '1 John', chapter: 3, verse: 23 },
  { book: '1 John', chapter: 4, verse: 1 },
  { book: '1 John', chapter: 4, verse: 2 },
  { book: '1 John', chapter: 5, verse: 11 },
  { book: '1 John', chapter: 5, verse: 13 },
  { book: '1 John', chapter: 5, verse: 20 },
  { book: '1 John', chapter: 5, verse: 5 },
  { book: '1 Peter', chapter: 1, verse: 21 },
  { book: '1 Peter', chapter: 1, verse: 8 },
  { book: '1 Peter', chapter: 2, verse: 17 },
  { book: '1 Peter', chapter: 3, verse: 4 },
  { book: '1 Thessalonians', chapter: 2, verse: 10 },
  { book: '1 Thessalonians', chapter: 2, verse: 12 },
  { book: '1 Thessalonians', chapter: 2, verse: 19 },
  { book: '1 Thessalonians', chapter: 2, verse: 6 },
  { book: '1 Thessalonians', chapter: 2, verse: 8 },
  { book: '1 Thessalonians', chapter: 3, verse: 11 },
  { book: '1 Thessalonians', chapter: 4, verse: 1 },
  { book: '1 Thessalonians', chapter: 4, verse: 8 },
  { book: '1 Thessalonians', chapter: 5, verse: 14 },
  { book: '1 Timothy', chapter: 1, verse: 11 },
  { book: '1 Timothy', chapter: 1, verse: 15 },
  { book: '1 Timothy', chapter: 2, verse: 3 },
  { book: '1 Timothy', chapter: 3, verse: 13 },
  { book: '1 Timothy', chapter: 6, verse: 12 },
  { book: '1 Timothy', chapter: 6, verse: 16 },
  { book: '1 Timothy', chapter: 6, verse: 3 },
  { book: '2 Corinthians', chapter: 1, verse: 11 },
  { book: '2 Corinthians', chapter: 1, verse: 20 },
  { book: '2 Corinthians', chapter: 4, verse: 1 },
  { book: '2 Corinthians', chapter: 4, verse: 15 },
  { book: '2 Corinthians', chapter: 6, verse: 8 },
  { book: '2 Corinthians', chapter: 7, verse: 1 },
  { book: '2 Corinthians', chapter: 7, verse: 13 },
  { book: '2 Corinthians', chapter: 8, verse: 9 },
  { book: '2 Corinthians', chapter: 9, verse: 7 },
  { book: '2 Corinthians', chapter: 9, verse: 9 },
  { book: '2 Peter', chapter: 1, verse: 1 },
  { book: '2 Timothy', chapter: 1, verse: 13 },
  { book: '2 Timothy', chapter: 1, verse: 3 },
  { book: '2 Timothy', chapter: 3, verse: 10 },
  { book: 'Acts', chapter: 1, verse: 4 },
  { book: 'Acts', chapter: 10, verse: 36 },
  { book: 'Acts', chapter: 12, verse: 23 },
  { book: 'Acts', chapter: 13, verse: 2 },
  { book: 'Acts', chapter: 13, verse: 23 },
  { book: 'Acts', chapter: 13, verse: 32 },
  { book: 'Acts', chapter: 15, verse: 8 },
  { book: 'Acts', chapter: 16, verse: 31 },
  { book: 'Acts', chapter: 20, verse: 24 },
  { book: 'Acts', chapter: 4, verse: 33 },
  { book: 'Acts', chapter: 5, verse: 31 },
  { book: 'Acts', chapter: 5, verse: 32 },
  { book: 'Acts', chapter: 8, verse: 12 },
  { book: 'Acts', chapter: 8, verse: 16 },
  { book: 'Colossians', chapter: 1, verse: 4 },
  { book: 'Colossians', chapter: 1, verse: 5 },
  { book: 'Colossians', chapter: 1, verse: 7 },
  { book: 'Colossians', chapter: 2, verse: 2 },
  { book: 'Colossians', chapter: 4, verse: 11 },
  { book: 'Colossians', chapter: 4, verse: 7 },
  { book: 'Ephesians', chapter: 1, verse: 14 },
  { book: 'Ephesians', chapter: 1, verse: 15 },
  { book: 'Ephesians', chapter: 2, verse: 5 },
  { book: 'Ephesians', chapter: 3, verse: 11 },
  { book: 'Ephesians', chapter: 3, verse: 7 },
  { book: 'Ephesians', chapter: 4, verse: 7 },
  { book: 'Ephesians', chapter: 5, verse: 19 },
  { book: 'Ephesians', chapter: 6, verse: 21 },
  { book: 'Galatians', chapter: 1, verse: 1 },
  { book: 'Galatians', chapter: 2, verse: 21 },
  { book: 'Galatians', chapter: 3, verse: 8 },
  { book: 'Galatians', chapter: 4, verse: 6 },
  { book: 'Hebrews', chapter: 11, verse: 21 },
  { book: 'Hebrews', chapter: 13, verse: 15 },
  { book: 'Hebrews', chapter: 13, verse: 21 },
  { book: 'Hebrews', chapter: 2, verse: 4 },
  { book: 'Hebrews', chapter: 6, verse: 18 },
  { book: 'Hebrews', chapter: 6, verse: 4 },
  { book: 'Isaiah', chapter: 12, verse: 4 },
  { book: 'Isaiah', chapter: 30, verse: 15 },
  { book: 'Isaiah', chapter: 30, verse: 29 },
  { book: 'Isaiah', chapter: 32, verse: 18 },
  { book: 'Isaiah', chapter: 41, verse: 14 },
  { book: 'Isaiah', chapter: 41, verse: 16 },
  { book: 'Isaiah', chapter: 43, verse: 4 },
  { book: 'Isaiah', chapter: 44, verse: 17 },
  { book: 'Isaiah', chapter: 49, verse: 13 },
  { book: 'Isaiah', chapter: 52, verse: 10 },
  { book: 'Isaiah', chapter: 61, verse: 1 },
  { book: 'James', chapter: 1, verse: 1 },
  { book: 'James', chapter: 2, verse: 1 },
  { book: 'James', chapter: 2, verse: 5 },
  { book: 'James', chapter: 4, verse: 6 },
  { book: 'James', chapter: 5, verse: 8 },
  { book: 'Jeremiah', chapter: 29, verse: 10 },
  { book: 'Jeremiah', chapter: 31, verse: 18 },
  { book: 'Jeremiah', chapter: 31, verse: 7 },
  { book: 'John', chapter: 11, verse: 27 },
  { book: 'John', chapter: 11, verse: 40 },
  { book: 'John', chapter: 12, verse: 43 },
  { book: 'John', chapter: 13, verse: 3 },
  { book: 'John', chapter: 16, verse: 27 },
  { book: 'John', chapter: 20, verse: 29 },
  { book: 'John', chapter: 21, verse: 16 },
  { book: 'John', chapter: 3, verse: 5 },
  { book: 'John', chapter: 4, verse: 10 },
  { book: 'John', chapter: 4, verse: 24 },
  { book: 'John', chapter: 5, verse: 44 },
  { book: 'John', chapter: 6, verse: 23 },
  { book: 'John', chapter: 6, verse: 27 },
  { book: 'John', chapter: 6, verse: 40 },
  { book: 'John', chapter: 8, verse: 42 },
  { book: 'John', chapter: 8, verse: 54 },
  { book: 'Joshua', chapter: 1, verse: 13 },
  { book: 'Lamentations', chapter: 3, verse: 25 },
  { book: 'Lamentations', chapter: 3, verse: 26 },
  { book: 'Luke', chapter: 1, verse: 14 },
  { book: 'Luke', chapter: 1, verse: 17 },
  { book: 'Luke', chapter: 1, verse: 32 },
  { book: 'Luke', chapter: 1, verse: 45 },
  { book: 'Luke', chapter: 12, verse: 42 },
  { book: 'Luke', chapter: 14, verse: 15 },
  { book: 'Luke', chapter: 18, verse: 43 },
  { book: 'Luke', chapter: 2, verse: 11 },
  { book: 'Luke', chapter: 2, verse: 14 },
  { book: 'Luke', chapter: 2, verse: 25 },
  { book: 'Luke', chapter: 23, verse: 34 },
  { book: 'Luke', chapter: 5, verse: 20 },
  { book: 'Luke', chapter: 6, verse: 12 },
  { book: 'Luke', chapter: 6, verse: 20 },
  { book: 'Luke', chapter: 7, verse: 50 },
  { book: 'Luke', chapter: 8, verse: 48 },
  { book: 'Mark', chapter: 10, verse: 17 },
  { book: 'Mark', chapter: 14, verse: 61 },
  { book: 'Mark', chapter: 2, verse: 5 },
  { book: 'Matthew', chapter: 1, verse: 16 },
  { book: 'Matthew', chapter: 12, verse: 18 },
  { book: 'Matthew', chapter: 18, verse: 21 },
  { book: 'Matthew', chapter: 18, verse: 35 },
  { book: 'Matthew', chapter: 19, verse: 16 },
  { book: 'Matthew', chapter: 20, verse: 30 },
  { book: 'Matthew', chapter: 9, verse: 22 },
  { book: 'Micah', chapter: 7, verse: 7 },
  { book: 'Philippians', chapter: 3, verse: 9 },
  { book: 'Proverbs', chapter: 16, verse: 13 },
  { book: 'Proverbs', chapter: 16, verse: 20 },
  { book: 'Proverbs', chapter: 31, verse: 28 },
  { book: 'Psalms', chapter: 100, verse: 2 },
  { book: 'Psalms', chapter: 104, verse: 31 },
  { book: 'Psalms', chapter: 111, verse: 1 },
  { book: 'Psalms', chapter: 112, verse: 7 },
  { book: 'Psalms', chapter: 113, verse: 1 },
  { book: 'Psalms', chapter: 113, verse: 2 },
  { book: 'Psalms', chapter: 118, verse: 15 },
  { book: 'Psalms', chapter: 118, verse: 19 },
  { book: 'Psalms', chapter: 124, verse: 6 },
  { book: 'Psalms', chapter: 145, verse: 10 },
  { book: 'Psalms', chapter: 145, verse: 2 },
  { book: 'Psalms', chapter: 147, verse: 7 },
  { book: 'Psalms', chapter: 18, verse: 3 },
  { book: 'Psalms', chapter: 18, verse: 35 },
  { book: 'Psalms', chapter: 18, verse: 49 },
  { book: 'Psalms', chapter: 19, verse: 8 },
  { book: 'Psalms', chapter: 23, verse: 3 },
  { book: 'Psalms', chapter: 28, verse: 6 },
  { book: 'Psalms', chapter: 28, verse: 9 },
  { book: 'Psalms', chapter: 30, verse: 2 },
  { book: 'Psalms', chapter: 32, verse: 1 },
  { book: 'Psalms', chapter: 33, verse: 12 },
  { book: 'Psalms', chapter: 33, verse: 17 },
  { book: 'Psalms', chapter: 33, verse: 21 },
  { book: 'Psalms', chapter: 34, verse: 1 },
  { book: 'Psalms', chapter: 34, verse: 12 },
  { book: 'Psalms', chapter: 40, verse: 11 },
  { book: 'Psalms', chapter: 40, verse: 17 },
  { book: 'Psalms', chapter: 40, verse: 4 },
  { book: 'Psalms', chapter: 40, verse: 8 },
  { book: 'Psalms', chapter: 48, verse: 10 },
  { book: 'Psalms', chapter: 62, verse: 8 },
  { book: 'Psalms', chapter: 63, verse: 7 },
  { book: 'Psalms', chapter: 65, verse: 1 },
  { book: 'Psalms', chapter: 65, verse: 5 },
  { book: 'Psalms', chapter: 66, verse: 20 },
  { book: 'Psalms', chapter: 66, verse: 8 },
  { book: 'Psalms', chapter: 84, verse: 12 },
  { book: 'Psalms', chapter: 84, verse: 4 },
  { book: 'Psalms', chapter: 84, verse: 5 },
  { book: 'Psalms', chapter: 84, verse: 8 },
  { book: 'Psalms', chapter: 85, verse: 10 },
  { book: 'Psalms', chapter: 85, verse: 9 },
  { book: 'Psalms', chapter: 86, verse: 11 },
  { book: 'Psalms', chapter: 86, verse: 2 },
  { book: 'Psalms', chapter: 9, verse: 1 },
  { book: 'Psalms', chapter: 9, verse: 14 },
  { book: 'Psalms', chapter: 90, verse: 14 },
  { book: 'Psalms', chapter: 92, verse: 4 },
  { book: 'Psalms', chapter: 95, verse: 1 },
  { book: 'Psalms', chapter: 96, verse: 13 },
  { book: 'Psalms', chapter: 96, verse: 2 },
  { book: 'Psalms', chapter: 96, verse: 4 },
  { book: 'Psalms', chapter: 97, verse: 11 },
  { book: 'Psalms', chapter: 98, verse: 1 },
  { book: 'Psalms', chapter: 98, verse: 5 },
  { book: 'Romans', chapter: 1, verse: 8 },
  { book: 'Romans', chapter: 10, verse: 1 },
  { book: 'Romans', chapter: 10, verse: 6 },
  { book: 'Romans', chapter: 12, verse: 1 },
  { book: 'Romans', chapter: 12, verse: 6 },
  { book: 'Romans', chapter: 14, verse: 18 },
  { book: 'Romans', chapter: 2, verse: 10 },
  { book: 'Romans', chapter: 4, verse: 24 },
  { book: 'Romans', chapter: 4, verse: 5 },
  { book: 'Romans', chapter: 4, verse: 6 },
  { book: 'Romans', chapter: 4, verse: 7 },
  { book: 'Romans', chapter: 6, verse: 11 },
  { book: 'Romans', chapter: 8, verse: 10 },
  { book: 'Romans', chapter: 8, verse: 34 },
  { book: 'Romans', chapter: 9, verse: 1 },
  { book: 'Titus', chapter: 1, verse: 9 },
  { book: 'Titus', chapter: 2, verse: 10 },
  { book: 'Titus', chapter: 3, verse: 4 },
  { book: 'Titus', chapter: 3, verse: 6 },
  { book: 'Titus', chapter: 3, verse: 7 },
  { book: '1 Corinthians', chapter: 1, verse: 1 },
  { book: '1 Corinthians', chapter: 1, verse: 24 },
  { book: '1 Corinthians', chapter: 1, verse: 25 },
  { book: '1 Corinthians', chapter: 10, verse: 33 },
  { book: '1 Corinthians', chapter: 12, verse: 24 },
  { book: '1 Corinthians', chapter: 12, verse: 7 },
  { book: '1 Corinthians', chapter: 13, verse: 7 },
  { book: '1 Corinthians', chapter: 14, verse: 1 },
  { book: '1 Corinthians', chapter: 14, verse: 25 },
  { book: '1 Corinthians', chapter: 15, verse: 19 },
  { book: '1 Corinthians', chapter: 15, verse: 38 },
  { book: '1 Corinthians', chapter: 15, verse: 58 },
  { book: '1 Corinthians', chapter: 16, verse: 7 },
  { book: '1 Corinthians', chapter: 2, verse: 12 },
  { book: '1 Corinthians', chapter: 2, verse: 7 },
  { book: '1 Corinthians', chapter: 2, verse: 9 },
  { book: '1 Corinthians', chapter: 3, verse: 10 },
  { book: '1 Corinthians', chapter: 3, verse: 16 },
  { book: '1 Corinthians', chapter: 4, verse: 15 },
  { book: '1 Corinthians', chapter: 4, verse: 21 },
  { book: '1 Corinthians', chapter: 5, verse: 4 },
  { book: '1 Corinthians', chapter: 5, verse: 5 },
  { book: '1 Corinthians', chapter: 6, verse: 11 },
  { book: '1 Corinthians', chapter: 6, verse: 19 },
  { book: '1 Corinthians', chapter: 7, verse: 15 },
  { book: '1 Corinthians', chapter: 7, verse: 17 },
  { book: '1 Corinthians', chapter: 7, verse: 35 },
  { book: '1 Corinthians', chapter: 8, verse: 6 },
  { book: '1 John', chapter: 2, verse: 17 },
  { book: '1 John', chapter: 2, verse: 22 },
  { book: '1 John', chapter: 2, verse: 25 },
  { book: '1 John', chapter: 3, verse: 16 },
  { book: '1 John', chapter: 3, verse: 17 },
  { book: '1 John', chapter: 3, verse: 21 },
  { book: '1 John', chapter: 3, verse: 24 },
  { book: '1 John', chapter: 3, verse: 9 },
  { book: '1 John', chapter: 4, verse: 15 },
  { book: '1 Peter', chapter: 1, verse: 22 },
  { book: '1 Peter', chapter: 1, verse: 5 },
  { book: '1 Peter', chapter: 2, verse: 2 },
  { book: '1 Peter', chapter: 2, verse: 5 },
  { book: '1 Peter', chapter: 3, verse: 5 },
  { book: '1 Peter', chapter: 3, verse: 8 },
  { book: '1 Peter', chapter: 4, verse: 18 },
  { book: '1 Peter', chapter: 5, verse: 14 },
  { book: '1 Thessalonians', chapter: 1, verse: 9 },
  { book: '1 Thessalonians', chapter: 2, verse: 4 },
  { book: '1 Thessalonians', chapter: 4, verse: 14 },
  { book: '1 Timothy', chapter: 1, verse: 5 },
  { book: '1 Timothy', chapter: 2, verse: 10 },
  { book: '1 Timothy', chapter: 2, verse: 15 },
  { book: '1 Timothy', chapter: 2, verse: 5 },
  { book: '1 Timothy', chapter: 4, verse: 4 },
  { book: '1 Timothy', chapter: 4, verse: 8 },
  { book: '1 Timothy', chapter: 5, verse: 21 },
  { book: '1 Timothy', chapter: 5, verse: 5 },
  { book: '1 Timothy', chapter: 6, verse: 14 },
  { book: '1 Timothy', chapter: 6, verse: 15 },
  { book: '2 Corinthians', chapter: 1, verse: 1 },
  { book: '2 Corinthians', chapter: 1, verse: 18 },
  { book: '2 Corinthians', chapter: 1, verse: 19 },
  { book: '2 Corinthians', chapter: 1, verse: 24 },
  { book: '2 Corinthians', chapter: 10, verse: 1 },
  { book: '2 Corinthians', chapter: 12, verse: 19 },
  { book: '2 Corinthians', chapter: 13, verse: 5 },
  { book: '2 Corinthians', chapter: 2, verse: 10 },
  { book: '2 Corinthians', chapter: 2, verse: 13 },
  { book: '2 Corinthians', chapter: 2, verse: 14 },
  { book: '2 Corinthians', chapter: 2, verse: 15 },
  { book: '2 Corinthians', chapter: 3, verse: 17 },
  { book: '2 Corinthians', chapter: 4, verse: 13 },
  { book: '2 Corinthians', chapter: 4, verse: 5 },
  { book: '2 Corinthians', chapter: 5, verse: 11 },
  { book: '2 Corinthians', chapter: 5, verse: 5 },
  { book: '2 Corinthians', chapter: 6, verse: 18 },
  { book: '2 Corinthians', chapter: 6, verse: 7 },
  { book: '2 Corinthians', chapter: 7, verse: 6 },
  { book: '2 Corinthians', chapter: 8, verse: 1 },
  { book: '2 Corinthians', chapter: 8, verse: 16 },
  { book: '2 Corinthians', chapter: 9, verse: 8 },
  { book: '2 Peter', chapter: 1, verse: 14 },
  { book: '2 Peter', chapter: 1, verse: 16 },
  { book: '2 Peter', chapter: 1, verse: 17 },
  { book: '2 Peter', chapter: 1, verse: 21 },
  { book: '2 Peter', chapter: 1, verse: 7 },
  { book: '2 Peter', chapter: 2, verse: 20 },
  { book: '2 Peter', chapter: 2, verse: 5 },
  { book: '2 Peter', chapter: 3, verse: 2 },
  { book: '2 Thessalonians', chapter: 1, verse: 9 },
  { book: '2 Thessalonians', chapter: 2, verse: 1 },
  { book: '2 Thessalonians', chapter: 3, verse: 12 },
  { book: '2 Thessalonians', chapter: 3, verse: 16 },
  { book: '2 Timothy', chapter: 2, verse: 1 },
  { book: '2 Timothy', chapter: 2, verse: 2 },
  { book: '2 Timothy', chapter: 2, verse: 25 },
  { book: '2 Timothy', chapter: 4, verse: 1 },
  { book: 'Acts', chapter: 1, verse: 16 },
  { book: 'Acts', chapter: 1, verse: 6 },
  { book: 'Acts', chapter: 10, verse: 31 },
  { book: 'Acts', chapter: 10, verse: 43 },
  { book: 'Acts', chapter: 11, verse: 16 },
  { book: 'Acts', chapter: 11, verse: 20 },
  { book: 'Acts', chapter: 13, verse: 33 },
  { book: 'Acts', chapter: 13, verse: 36 },
  { book: 'Acts', chapter: 13, verse: 38 },
  { book: 'Acts', chapter: 13, verse: 47 },
  { book: 'Acts', chapter: 13, verse: 52 },
  { book: 'Acts', chapter: 14, verse: 22 },
  { book: 'Acts', chapter: 14, verse: 23 },
  { book: 'Acts', chapter: 15, verse: 26 },
  { book: 'Acts', chapter: 15, verse: 28 },
  { book: 'Acts', chapter: 15, verse: 32 },
  { book: 'Acts', chapter: 16, verse: 17 },
  { book: 'Acts', chapter: 16, verse: 34 },
  { book: 'Acts', chapter: 17, verse: 25 },
  { book: 'Acts', chapter: 18, verse: 25 },
  { book: 'Acts', chapter: 19, verse: 17 },
  { book: 'Acts', chapter: 19, verse: 2 },
  { book: 'Acts', chapter: 2, verse: 32 },
  { book: 'Acts', chapter: 2, verse: 39 },
  { book: 'Acts', chapter: 20, verse: 32 },
  { book: 'Acts', chapter: 3, verse: 20 },
  { book: 'Acts', chapter: 3, verse: 21 },
  { book: 'Acts', chapter: 3, verse: 6 },
  { book: 'Acts', chapter: 4, verse: 12 },
  { book: 'Acts', chapter: 4, verse: 25 },
  { book: 'Acts', chapter: 4, verse: 31 },
  { book: 'Acts', chapter: 5, verse: 3 },
  { book: 'Acts', chapter: 5, verse: 42 },
  { book: 'Acts', chapter: 7, verse: 17 },
  { book: 'Acts', chapter: 7, verse: 20 },
  { book: 'Acts', chapter: 7, verse: 25 },
  { book: 'Acts', chapter: 7, verse: 59 },
  { book: 'Acts', chapter: 8, verse: 19 },
  { book: 'Colossians', chapter: 1, verse: 1 },
  { book: 'Colossians', chapter: 1, verse: 10 },
  { book: 'Colossians', chapter: 1, verse: 11 },
  { book: 'Colossians', chapter: 1, verse: 12 },
  { book: 'Colossians', chapter: 2, verse: 13 },
  { book: 'Colossians', chapter: 2, verse: 6 },
  { book: 'Colossians', chapter: 3, verse: 13 },
  { book: 'Colossians', chapter: 3, verse: 3 },
  { book: 'Colossians', chapter: 3, verse: 4 },
  { book: 'Colossians', chapter: 4, verse: 12 },
  { book: 'Colossians', chapter: 4, verse: 8 },
  { book: 'Colossians', chapter: 4, verse: 9 },
  { book: 'Ephesians', chapter: 1, verse: 18 },
  { book: 'Ephesians', chapter: 1, verse: 19 },
  { book: 'Ephesians', chapter: 1, verse: 5 },
  { book: 'Ephesians', chapter: 2, verse: 22 },
  { book: 'Ephesians', chapter: 2, verse: 4 },
  { book: 'Ephesians', chapter: 2, verse: 6 },
  { book: 'Ephesians', chapter: 3, verse: 16 },
  { book: 'Ephesians', chapter: 3, verse: 19 },
  { book: 'Ephesians', chapter: 3, verse: 5 },
  { book: 'Ephesians', chapter: 3, verse: 6 },
  { book: 'Ephesians', chapter: 3, verse: 8 },
  { book: 'Ephesians', chapter: 4, verse: 13 },
  { book: 'Ephesians', chapter: 4, verse: 15 },
  { book: 'Ephesians', chapter: 4, verse: 18 },
  { book: 'Ephesians', chapter: 4, verse: 3 },
  { book: 'Ephesians', chapter: 4, verse: 30 },
  { book: 'Ephesians', chapter: 5, verse: 2 },
  { book: 'Ephesians', chapter: 6, verse: 18 },
  { book: 'Ephesians', chapter: 6, verse: 2 },
  { book: 'Ephesians', chapter: 6, verse: 22 },
  { book: 'Ephesians', chapter: 6, verse: 6 },
  { book: 'Galatians', chapter: 1, verse: 10 },
  { book: 'Galatians', chapter: 2, verse: 4 },
  { book: 'Galatians', chapter: 3, verse: 11 },
  { book: 'Galatians', chapter: 3, verse: 21 },
  { book: 'Galatians', chapter: 3, verse: 5 },
  { book: 'Galatians', chapter: 3, verse: 6 },
  { book: 'Galatians', chapter: 3, verse: 9 },
  { book: 'Galatians', chapter: 4, verse: 15 },
  { book: 'Galatians', chapter: 5, verse: 13 },
  { book: 'Galatians', chapter: 6, verse: 16 },
  { book: 'Galatians', chapter: 6, verse: 8 },
  { book: 'Hebrews', chapter: 1, verse: 14 },
  { book: 'Hebrews', chapter: 1, verse: 6 },
  { book: 'Hebrews', chapter: 1, verse: 8 },
  { book: 'Hebrews', chapter: 11, verse: 11 },
  { book: 'Hebrews', chapter: 11, verse: 20 },
  { book: 'Hebrews', chapter: 12, verse: 10 },
  { book: 'Hebrews', chapter: 12, verse: 11 },
  { book: 'Hebrews', chapter: 12, verse: 23 },
  { book: 'Hebrews', chapter: 13, verse: 7 },
  { book: 'Hebrews', chapter: 2, verse: 12 },
  { book: 'Hebrews', chapter: 2, verse: 13 },
  { book: 'Hebrews', chapter: 3, verse: 2 },
  { book: 'Hebrews', chapter: 3, verse: 3 },
  { book: 'Hebrews', chapter: 3, verse: 5 },
  { book: 'Hebrews', chapter: 4, verse: 8 },
  { book: 'Hebrews', chapter: 6, verse: 12 },
  { book: 'Hebrews', chapter: 6, verse: 5 },
  { book: 'Hebrews', chapter: 6, verse: 7 },
  { book: 'Hebrews', chapter: 7, verse: 19 },
  { book: 'Hebrews', chapter: 7, verse: 21 },
  { book: 'Hebrews', chapter: 7, verse: 25 },
  { book: 'Hebrews', chapter: 7, verse: 3 },
  { book: 'Hebrews', chapter: 7, verse: 6 },
  { book: 'Isaiah', chapter: 26, verse: 18 },
  { book: 'Isaiah', chapter: 26, verse: 2 },
  { book: 'Isaiah', chapter: 30, verse: 2 },
  { book: 'Isaiah', chapter: 40, verse: 11 },
  { book: 'Isaiah', chapter: 40, verse: 13 },
  { book: 'Isaiah', chapter: 43, verse: 12 },
  { book: 'Isaiah', chapter: 44, verse: 3 },
  { book: 'Isaiah', chapter: 44, verse: 6 },
  { book: 'Isaiah', chapter: 46, verse: 13 },
  { book: 'Isaiah', chapter: 52, verse: 7 },
  { book: 'Isaiah', chapter: 61, verse: 11 },
  { book: 'Isaiah', chapter: 61, verse: 4 },
  { book: 'Isaiah', chapter: 65, verse: 23 },
  { book: 'James', chapter: 1, verse: 18 },
  { book: 'James', chapter: 2, verse: 14 },
  { book: 'James', chapter: 2, verse: 23 },
  { book: 'Jeremiah', chapter: 31, verse: 14 },
  { book: 'Jeremiah', chapter: 32, verse: 39 },
  { book: 'Jeremiah', chapter: 32, verse: 42 },
  { book: 'John', chapter: 10, verse: 17 },
  { book: 'John', chapter: 10, verse: 25 },
  { book: 'John', chapter: 10, verse: 28 },
  { book: 'John', chapter: 10, verse: 32 },
  { book: 'John', chapter: 11, verse: 3 },
  { book: 'John', chapter: 12, verse: 13 },
  { book: 'John', chapter: 12, verse: 25 },
  { book: 'John', chapter: 12, verse: 26 },
  { book: 'John', chapter: 12, verse: 50 },
  { book: 'John', chapter: 14, verse: 16 },
  { book: 'John', chapter: 14, verse: 17 },
  { book: 'John', chapter: 14, verse: 23 },
  { book: 'John', chapter: 14, verse: 26 },
  { book: 'John', chapter: 15, verse: 26 },
  { book: 'John', chapter: 17, verse: 2 },
  { book: 'John', chapter: 19, verse: 26 },
  { book: 'John', chapter: 2, verse: 11 },
  { book: 'John', chapter: 20, verse: 21 },
  { book: 'John', chapter: 3, verse: 15 },
  { book: 'John', chapter: 3, verse: 21 },
  { book: 'John', chapter: 3, verse: 3 },
  { book: 'John', chapter: 3, verse: 34 },
  { book: 'John', chapter: 4, verse: 20 },
  { book: 'John', chapter: 4, verse: 23 },
  { book: 'John', chapter: 4, verse: 36 },
  { book: 'John', chapter: 4, verse: 53 },
  { book: 'John', chapter: 5, verse: 21 },
  { book: 'John', chapter: 6, verse: 29 },
  { book: 'John', chapter: 6, verse: 33 },
  { book: 'John', chapter: 6, verse: 47 },
  { book: 'John', chapter: 6, verse: 63 },
  { book: 'John', chapter: 6, verse: 68 },
  { book: 'John', chapter: 6, verse: 69 },
  { book: 'John', chapter: 7, verse: 18 },
  { book: 'John', chapter: 8, verse: 49 },
  { book: 'John', chapter: 8, verse: 56 },
  { book: 'John', chapter: 9, verse: 24 },
  { book: 'Joshua', chapter: 1, verse: 6 },
  { book: 'Lamentations', chapter: 3, verse: 18 },
  { book: 'Luke', chapter: 1, verse: 48 },
  { book: 'Luke', chapter: 1, verse: 55 },
  { book: 'Luke', chapter: 1, verse: 58 },
  { book: 'Luke', chapter: 1, verse: 6 },
  { book: 'Luke', chapter: 1, verse: 67 },
  { book: 'Luke', chapter: 10, verse: 23 },
  { book: 'Luke', chapter: 10, verse: 27 },
  { book: 'Luke', chapter: 11, verse: 28 },
  { book: 'Luke', chapter: 13, verse: 23 },
  { book: 'Luke', chapter: 13, verse: 35 },
  { book: 'Luke', chapter: 14, verse: 14 },
  { book: 'Luke', chapter: 16, verse: 11 },
  { book: 'Luke', chapter: 16, verse: 12 },
  { book: 'Luke', chapter: 17, verse: 15 },
  { book: 'Luke', chapter: 17, verse: 18 },
  { book: 'Luke', chapter: 17, verse: 33 },
  { book: 'Luke', chapter: 18, verse: 18 },
  { book: 'Luke', chapter: 18, verse: 19 },
  { book: 'Luke', chapter: 18, verse: 42 },
  { book: 'Luke', chapter: 19, verse: 17 },
  { book: 'Luke', chapter: 19, verse: 37 },
  { book: 'Luke', chapter: 2, verse: 20 },
  { book: 'Luke', chapter: 2, verse: 29 },
  { book: 'Luke', chapter: 2, verse: 40 },
  { book: 'Luke', chapter: 2, verse: 52 },
  { book: 'Luke', chapter: 20, verse: 25 },
  { book: 'Luke', chapter: 22, verse: 67 },
  { book: 'Luke', chapter: 23, verse: 35 },
  { book: 'Luke', chapter: 23, verse: 46 },
  { book: 'Luke', chapter: 23, verse: 47 },
  { book: 'Luke', chapter: 24, verse: 25 },
  { book: 'Luke', chapter: 24, verse: 50 },
  { book: 'Luke', chapter: 3, verse: 15 },
  { book: 'Luke', chapter: 3, verse: 22 },
  { book: 'Luke', chapter: 4, verse: 1 },
  { book: 'Luke', chapter: 4, verse: 12 },
  { book: 'Luke', chapter: 4, verse: 43 },
  { book: 'Luke', chapter: 5, verse: 1 },
  { book: 'Luke', chapter: 7, verse: 43 },
  { book: 'Luke', chapter: 7, verse: 47 },
  { book: 'Luke', chapter: 8, verse: 50 },
  { book: 'Luke', chapter: 9, verse: 20 },
  { book: 'Luke', chapter: 9, verse: 32 },
  { book: 'Mark', chapter: 1, verse: 1 },
  { book: 'Mark', chapter: 1, verse: 14 },
  { book: 'Mark', chapter: 1, verse: 15 },
  { book: 'Mark', chapter: 10, verse: 18 },
  { book: 'Mark', chapter: 10, verse: 45 },
  { book: 'Mark', chapter: 10, verse: 52 },
  { book: 'Mark', chapter: 11, verse: 10 },
  { book: 'Mark', chapter: 11, verse: 25 },
  { book: 'Mark', chapter: 11, verse: 9 },
  { book: 'Mark', chapter: 12, verse: 17 },
  { book: 'Mark', chapter: 12, verse: 29 },
  { book: 'Mark', chapter: 12, verse: 36 },
  { book: 'Mark', chapter: 12, verse: 37 },
  { book: 'Mark', chapter: 14, verse: 22 },
  { book: 'Mark', chapter: 15, verse: 43 },
  { book: 'Mark', chapter: 16, verse: 11 },
  { book: 'Mark', chapter: 16, verse: 19 },
  { book: 'Mark', chapter: 2, verse: 8 },
  { book: 'Mark', chapter: 5, verse: 19 },
  { book: 'Mark', chapter: 7, verse: 11 },
  { book: 'Mark', chapter: 8, verse: 12 },
  { book: 'Mark', chapter: 8, verse: 25 },
  { book: 'Mark', chapter: 8, verse: 7 },
  { book: 'Mark', chapter: 9, verse: 24 },
  { book: 'Mark', chapter: 9, verse: 29 },
  { book: 'Mark', chapter: 9, verse: 9 },
  { book: 'Matthew', chapter: 1, verse: 21 },
  { book: 'Matthew', chapter: 11, verse: 25 },
  { book: 'Matthew', chapter: 12, verse: 13 },
  { book: 'Matthew', chapter: 14, verse: 30 },
  { book: 'Matthew', chapter: 15, verse: 28 },
  { book: 'Matthew', chapter: 15, verse: 31 },
  { book: 'Matthew', chapter: 15, verse: 5 },
  { book: 'Matthew', chapter: 15, verse: 6 },
  { book: 'Matthew', chapter: 17, verse: 11 },
  { book: 'Matthew', chapter: 17, verse: 4 },
  { book: 'Matthew', chapter: 19, verse: 17 },
  { book: 'Matthew', chapter: 19, verse: 19 },
  { book: 'Matthew', chapter: 2, verse: 10 },
  { book: 'Matthew', chapter: 20, verse: 28 },
  { book: 'Matthew', chapter: 22, verse: 21 },
  { book: 'Matthew', chapter: 22, verse: 43 },
  { book: 'Matthew', chapter: 23, verse: 39 },
  { book: 'Matthew', chapter: 24, verse: 45 },
  { book: 'Matthew', chapter: 25, verse: 34 },
  { book: 'Matthew', chapter: 25, verse: 37 },
  { book: 'Matthew', chapter: 26, verse: 26 },
  { book: 'Matthew', chapter: 26, verse: 63 },
  { book: 'Matthew', chapter: 27, verse: 43 },
  { book: 'Matthew', chapter: 28, verse: 19 },
  { book: 'Matthew', chapter: 4, verse: 7 },
  { book: 'Matthew', chapter: 5, verse: 3 },
  { book: 'Matthew', chapter: 5, verse: 6 },
  { book: 'Matthew', chapter: 5, verse: 7 },
  { book: 'Matthew', chapter: 6, verse: 14 },
  { book: 'Matthew', chapter: 8, verse: 13 },
  { book: 'Matthew', chapter: 8, verse: 16 },
  { book: 'Matthew', chapter: 9, verse: 28 },
  { book: 'Micah', chapter: 7, verse: 20 },
  { book: 'Nehemiah', chapter: 8, verse: 6 },
  { book: 'Philippians', chapter: 1, verse: 8 },
  { book: 'Philippians', chapter: 2, verse: 17 },
  { book: 'Philippians', chapter: 2, verse: 19 },
  { book: 'Philippians', chapter: 2, verse: 2 },
  { book: 'Philippians', chapter: 2, verse: 21 },
  { book: 'Philippians', chapter: 2, verse: 29 },
  { book: 'Philippians', chapter: 2, verse: 30 },
  { book: 'Philippians', chapter: 4, verse: 1 },
  { book: 'Philippians', chapter: 4, verse: 18 },
  { book: 'Philippians', chapter: 4, verse: 5 },
  { book: 'Proverbs', chapter: 11, verse: 6 },
  { book: 'Proverbs', chapter: 12, verse: 8 },
  { book: 'Proverbs', chapter: 13, verse: 12 },
  { book: 'Proverbs', chapter: 13, verse: 2 },
  { book: 'Proverbs', chapter: 14, verse: 21 },
  { book: 'Proverbs', chapter: 14, verse: 26 },
  { book: 'Proverbs', chapter: 14, verse: 33 },
  { book: 'Proverbs', chapter: 15, verse: 30 },
  { book: 'Proverbs', chapter: 15, verse: 33 },
  { book: 'Proverbs', chapter: 19, verse: 6 },
  { book: 'Proverbs', chapter: 20, verse: 28 },
  { book: 'Proverbs', chapter: 20, verse: 7 },
  { book: 'Proverbs', chapter: 21, verse: 21 },
  { book: 'Proverbs', chapter: 21, verse: 26 },
  { book: 'Proverbs', chapter: 3, verse: 18 },
  { book: 'Proverbs', chapter: 3, verse: 3 },
];
