import type { ImageSourcePropType } from 'react-native';
import type { AppLanguageKey } from '@/utils/app-settings';

const GENESIS_READING_IMAGE_SOURCES: ImageSourcePropType[] = [
  require('../assets/bible/genesis/chapter-01.png'),
  require('../assets/bible/genesis/chapter-02.png'),
  require('../assets/bible/genesis/chapter-03.png'),
  require('../assets/bible/genesis/chapter-04.png'),
  require('../assets/bible/genesis/chapter-05.png'),
  require('../assets/bible/genesis/chapter-06.png'),
  require('../assets/bible/genesis/chapter-07.png'),
  require('../assets/bible/genesis/chapter-08.png'),
  require('../assets/bible/genesis/chapter-09.png'),
  require('../assets/bible/genesis/chapter-10.png'),
  require('../assets/bible/genesis/chapter-11.png'),
  require('../assets/bible/genesis/chapter-12.png'),
  require('../assets/bible/genesis/chapter-13.png'),
  require('../assets/bible/genesis/chapter-14.png'),
  require('../assets/bible/genesis/chapter-15.png'),
  require('../assets/bible/genesis/chapter-16.png'),
  require('../assets/bible/genesis/chapter-17.png'),
  require('../assets/bible/genesis/chapter-18.png'),
  require('../assets/bible/genesis/chapter-19.png'),
  require('../assets/bible/genesis/chapter-20.png'),
  require('../assets/bible/genesis/chapter-21.png'),
  require('../assets/bible/genesis/chapter-22.png'),
  require('../assets/bible/genesis/chapter-23.png'),
  require('../assets/bible/genesis/chapter-24.png'),
  require('../assets/bible/genesis/chapter-25.png'),
  require('../assets/bible/genesis/chapter-26.png'),
  require('../assets/bible/genesis/chapter-27.png'),
  require('../assets/bible/genesis/chapter-28.png'),
  require('../assets/bible/genesis/chapter-29.png'),
  require('../assets/bible/genesis/chapter-30.png'),
  require('../assets/bible/genesis/chapter-31.png'),
  require('../assets/bible/genesis/chapter-32.png'),
  require('../assets/bible/genesis/chapter-33.png'),
  require('../assets/bible/genesis/chapter-34.png'),
  require('../assets/bible/genesis/chapter-35.png'),
  require('../assets/bible/genesis/chapter-36.png'),
  require('../assets/bible/genesis/chapter-37.png'),
  require('../assets/bible/genesis/chapter-38.png'),
  require('../assets/bible/genesis/chapter-39.png'),
  require('../assets/bible/genesis/chapter-40.png'),
  require('../assets/bible/genesis/chapter-41.png'),
  require('../assets/bible/genesis/chapter-42.png'),
  require('../assets/bible/genesis/chapter-43.png'),
  require('../assets/bible/genesis/chapter-44.png'),
  require('../assets/bible/genesis/chapter-45.png'),
  require('../assets/bible/genesis/chapter-46.png'),
  require('../assets/bible/genesis/chapter-47.png'),
  require('../assets/bible/genesis/chapter-48.png'),
  require('../assets/bible/genesis/chapter-49.png'),
  require('../assets/bible/genesis/chapter-50.png'),
];

export type GenesisReadingImage = {
  chapter: number;
  title: LocalizedReadingText;
  summary: LocalizedReadingText;
  visualCue: string;
  image: ImageSourcePropType;
};

type LocalizedReadingText = { en: string } & Partial<Record<AppLanguageKey, string>>;

const chapterSummaries = [
  ['Light and Life', 'God fills an empty world with light, sky, land, plants, stars, animals, and people made with care.', 'Sunrise, stars, water, and garden leaves'],
  ['A Garden Home', 'God gives people a beautiful garden, meaningful work, rest, and close friendship with Him.', 'Garden path, river, trees, and warm light'],
  ['Choices and Mercy', 'A sad choice changes the garden, but God still cares for His children and promises hope.', 'Soft leaves, a guarded path, and a hopeful glow'],
  ['A Hurting Family', 'The first family faces jealousy and sorrow, and God keeps speaking with mercy and truth.', 'Two paths, quiet field, and a gentle light'],
  ['Family Stories Grow', 'Generations pass from Adam to Noah, showing that every family story matters to God.', 'Family tree, stars, and small homes'],
  ['Noah Listens', 'In a noisy world, Noah listens to God and prepares a safe place for his family.', 'Warm ark shape, soft clouds, and paired animals'],
  ['Shelter in Rain', 'Rain covers the earth, and God keeps Noah, his family, and the animals safe inside the ark.', 'Rainy sky, sheltering ark, and calm window light'],
  ['A Fresh Start', 'The water settles, a dove searches for dry land, and the world begins again.', 'Dove, olive leaf, and quiet morning hills'],
  ['Rainbow Promise', 'God gives a rainbow promise and reminds Noahs family that life is precious.', 'Rainbow, clouds, and peaceful fields'],
  ['Families Spread Out', 'Noahs family grows into many families, places, and peoples across the earth.', 'Soft map paths, tents, and little hills'],
  ['Many Languages', 'People build for their own name, and God sends them out with many languages.', 'Tall tower shape, scattered paths, and bright sky'],
  ['A New Journey', 'God calls Abram to leave home and follow a promise into a new land.', 'Open road, tents, and morning stars'],
  ['Room for Peace', 'Abram and Lot choose space instead of fighting, and God renews His promise.', 'Wide fields, two paths, and peaceful tents'],
  ['A Brave Rescue', 'Abram helps his family and honors God after a hard season.', 'Lantern, shield-like hills, and thankful table'],
  ['Stars of Promise', 'God shows Abram the stars and promises a family too many to count.', 'Night sky, stars, and a quiet tent'],
  ['God Sees Hagar', 'Hagar feels alone, but God sees her, hears her, and cares for her future.', 'Desert spring, soft shade, and a path forward'],
  ['New Names', 'God gives Abram and Sarai new names and repeats His covenant promise.', 'Name scroll, stars, and family tent'],
  ['Visitors and Promise', 'Three visitors bring news of joy, and Abraham learns that nothing is too hard for God.', 'Shaded tree, table, and welcoming tent'],
  ['Guided to Safety', 'God leads Lot away from danger, and the story becomes a quiet warning to choose what is good.', 'Safe path, sunrise, and distant town shapes'],
  ['Promise Protected', 'God protects Sarah and Abraham even when fear makes things complicated.', 'Gentle doorway, promise light, and calm hills'],
  ['Isaac Brings Joy', 'Isaac is born, laughter fills the home, and God also cares for Hagar and Ishmael.', 'Cradle light, well, and joyful tent'],
  ['God Provides', 'Abraham learns to trust God deeply, and God provides what is needed on the mountain.', 'Mountain path, ram in the distance, and golden light'],
  ['Remembering Sarah', 'Abraham honors Sarah with love and care, choosing a resting place for her.', 'Soft flowers, quiet cave, and warm sunset'],
  ['Rebekah at the Well', 'A prayer at the well leads to Rebekah, kindness, and a new family story.', 'Well, water jar, bracelets, and gentle camels'],
  ['Twins and Choices', 'Jacob and Esau are born, and their family begins a complicated story of choices.', 'Two small paths, family tent, and warm stew bowl'],
  ['Wells of Peace', 'Isaac keeps choosing peace, and God reminds him of the promise given to Abraham.', 'Water wells, open land, and calm tents'],
  ['Blessing and Honesty', 'A family blessing is tangled with fear and trickery, showing why truth matters.', 'Hands, soft blanket pattern, and a quiet doorway'],
  ['A Ladder Dream', 'Jacob dreams of a stairway to heaven and hears that God is with him wherever he goes.', 'Starry ladder, stone pillow, and morning light'],
  ['Patient Love', 'Jacob works, waits, and grows through a complicated family season.', 'Pasture, sheep, and a home lit at dusk'],
  ['A Growing Family', "Jacob's family grows, and God keeps working through imperfect people.", 'Family tents, soft flowers, and little stars'],
  ['The Road Home', 'Jacob leaves with his family, trusting God to guide the way forward.', 'Packed tents, hillside road, and sunrise'],
  ['Night of Courage', 'Jacob prays through the night and receives a new name for a new chapter.', 'Riverbank, stars, and a glowing dawn'],
  ['Peaceful Meeting', 'Jacob and Esau meet again, and kindness makes room for peace.', 'Two paths meeting, open arms shape, and soft fields'],
  ['Wisdom After Hurt', 'A painful family story shows why wisdom, protection, and healing matter.', 'Mended cloth, quiet gate, and gentle light'],
  ['Back to Bethel', 'Jacob returns to worship, and God reminds him of his new name and promise.', 'Stone altar, oak tree, and bright sky'],
  ["Esau's Family", "Esau's family grows into many households and leaders.", 'Family tree, desert hills, and tents'],
  ['Joseph Dreams', "Joseph's dreams begin a long story, even when his family does not understand.", 'Colorful robe, stars, and wheat bundles'],
  ['Hope Continues', "A complicated family story still becomes part of God's bigger plan.", 'Thread, seal, staff, and warm sunrise'],
  ['Faithful in Hard Places', 'Joseph chooses faithfulness when life is unfair, and God stays with him.', 'Window light, folded cloak, and quiet room'],
  ['Dreams Remembered', 'Joseph helps others understand dreams while waiting for his own story to change.', 'Cup, bread basket, moon, and stars'],
  ['Wisdom for Tomorrow', 'God gives Joseph wisdom to prepare Egypt for years of plenty and hunger.', 'Grain, river, and storehouse baskets'],
  ['Brothers Seek Food', "Joseph's brothers travel for grain, and an old family story begins to turn.", 'Grain sacks, road, and distant tents'],
  ['A Second Journey', "The brothers return with Benjamin, carrying gifts and worry into Joseph's house.", 'Gift bundles, doorway, and warm table'],
  ['A Brother Protects', 'Judah offers himself for Benjamin, showing a heart that has changed.', 'Silver cup, travel bag, and protective hands'],
  ['Forgiveness Revealed', 'Joseph tells his brothers who he is and meets them with tears and forgiveness.', 'Open doorway, family table, and soft light'],
  ['Family Moves Together', "Jacob's family travels to Egypt, and God promises to go with them.", 'Wagons, tents, and evening stars'],
  ['Provision in Hunger', 'Joseph helps families through a hungry season and gives his own family a place to live.', 'Wheat, river fields, and full baskets'],
  ['Blessing the Children', "Jacob blesses Joseph's sons and remembers God's care across his life.", 'Grandfather hands, children silhouettes, and stars'],
  ['Words for the Family', 'Jacob speaks blessings over his sons and points toward the future.', 'Family circle, scroll, and candle glow'],
  ['Forgiveness and Hope', "Joseph chooses forgiveness again and trusts God's good plan for the future.", 'Path home, stars, and a peaceful sunrise'],
] as const;

const spanishChapterSummaries = [
  ['Luz y Vida', 'Dios llena un mundo vacío con luz, cielo, tierra, plantas, estrellas, animales y personas hechas con cuidado.'],
  ['Un Jardín Hogar', 'Dios da a las personas un jardín hermoso, trabajo con propósito, descanso y amistad cercana con Él.'],
  ['Decisiones y Misericordia', 'Una decisión triste cambia el jardín, pero Dios sigue cuidando a Sus hijos y promete esperanza.'],
  ['Una Familia Herida', 'La primera familia enfrenta celos y tristeza, y Dios sigue hablando con misericordia y verdad.'],
  ['Crecen las Historias Familiares', 'Las generaciones pasan de Adán a Noé, mostrando que cada historia familiar le importa a Dios.'],
  ['Noé Escucha', 'En un mundo ruidoso, Noé escucha a Dios y prepara un lugar seguro para su familia.'],
  ['Refugio en la Lluvia', 'La lluvia cubre la tierra, y Dios mantiene a Noé, su familia y los animales seguros dentro del arca.'],
  ['Un Nuevo Comienzo', 'El agua baja, una paloma busca tierra seca y el mundo empieza otra vez.'],
  ['Promesa del Arcoíris', 'Dios da una promesa con un arcoíris y recuerda a la familia de Noé que la vida es preciosa.'],
  ['Las Familias se Extienden', 'La familia de Noé crece en muchas familias, lugares y pueblos por toda la tierra.'],
  ['Muchos Idiomas', 'Las personas construyen para hacerse famosas, y Dios las envía con muchos idiomas.'],
  ['Un Nuevo Viaje', 'Dios llama a Abram a dejar su hogar y seguir una promesa hacia una nueva tierra.'],
  ['Espacio para la Paz', 'Abram y Lot eligen espacio en vez de pelear, y Dios renueva Su promesa.'],
  ['Un Rescate Valiente', 'Abram ayuda a su familia y honra a Dios después de una temporada difícil.'],
  ['Estrellas de Promesa', 'Dios muestra a Abram las estrellas y promete una familia demasiado grande para contar.'],
  ['Dios Ve a Agar', 'Agar se siente sola, pero Dios la ve, la escucha y cuida su futuro.'],
  ['Nombres Nuevos', 'Dios da nuevos nombres a Abram y Sarai y repite Su promesa de pacto.'],
  ['Visitantes y Promesa', 'Tres visitantes traen noticias de alegría, y Abraham aprende que nada es demasiado difícil para Dios.'],
  ['Guiados a Lugar Seguro', 'Dios aleja a Lot del peligro, y la historia recuerda elegir lo bueno.'],
  ['Promesa Protegida', 'Dios protege a Sara y Abraham aun cuando el miedo complica las cosas.'],
  ['Isaac Trae Alegría', 'Isaac nace, la risa llena el hogar, y Dios también cuida a Agar e Ismael.'],
  ['Dios Provee', 'Abraham aprende a confiar profundamente en Dios, y Dios provee lo necesario en la montaña.'],
  ['Recordando a Sara', 'Abraham honra a Sara con amor y cuidado, escogiendo un lugar de descanso para ella.'],
  ['Rebeca en el Pozo', 'Una oración en el pozo lleva a Rebeca, bondad y una nueva historia familiar.'],
  ['Gemelos y Decisiones', 'Jacob y Esaú nacen, y su familia empieza una historia complicada de decisiones.'],
  ['Pozos de Paz', 'Isaac sigue eligiendo paz, y Dios le recuerda la promesa dada a Abraham.'],
  ['Bendición y Honestidad', 'Una bendición familiar se enreda con miedo y engaño, mostrando por qué importa la verdad.'],
  ['Un Sueño de Escalera', 'Jacob sueña con una escalera al cielo y oye que Dios está con él dondequiera que vaya.'],
  ['Amor Paciente', 'Jacob trabaja, espera y crece durante una temporada familiar complicada.'],
  ['Una Familia que Crece', 'La familia de Jacob crece, y Dios sigue obrando por medio de personas imperfectas.'],
  ['El Camino a Casa', 'Jacob se va con su familia, confiando en que Dios guiará el camino.'],
  ['Noche de Valor', 'Jacob ora durante la noche y recibe un nombre nuevo para una nueva etapa.'],
  ['Encuentro de Paz', 'Jacob y Esaú se encuentran otra vez, y la bondad abre espacio para la paz.'],
  ['Sabiduría Después del Dolor', 'Una historia familiar dolorosa muestra por qué importan la sabiduría, la protección y la sanidad.'],
  ['Regreso a Betel', 'Jacob vuelve a adorar, y Dios le recuerda su nuevo nombre y Su promesa.'],
  ['La Familia de Esaú', 'La familia de Esaú crece en muchas casas y líderes.'],
  ['Los Sueños de José', 'Los sueños de José empiezan una larga historia, aun cuando su familia no entiende.'],
  ['La Esperanza Continúa', 'Una historia familiar complicada sigue formando parte del plan más grande de Dios.'],
  ['Fiel en Lugares Difíciles', 'José elige fidelidad cuando la vida es injusta, y Dios permanece con él.'],
  ['Sueños Recordados', 'José ayuda a otros a entender sueños mientras espera que su propia historia cambie.'],
  ['Sabiduría para Mañana', 'Dios da a José sabiduría para preparar a Egipto para años de abundancia y hambre.'],
  ['Hermanos Buscan Comida', 'Los hermanos de José viajan por grano, y una vieja historia familiar empieza a cambiar.'],
  ['Un Segundo Viaje', 'Los hermanos vuelven con Benjamín, llevando regalos y preocupación a la casa de José.'],
  ['Un Hermano Protege', 'Judá se ofrece por Benjamín, mostrando un corazón que ha cambiado.'],
  ['Perdón Revelado', 'José dice a sus hermanos quién es y los recibe con lágrimas y perdón.'],
  ['La Familia se Mueve Juntos', 'La familia de Jacob viaja a Egipto, y Dios promete ir con ellos.'],
  ['Provisión en el Hambre', 'José ayuda a familias durante el hambre y da a su propia familia un lugar para vivir.'],
  ['Bendición para los Niños', 'Jacob bendice a los hijos de José y recuerda el cuidado de Dios durante su vida.'],
  ['Palabras para la Familia', 'Jacob habla bendiciones sobre sus hijos y apunta hacia el futuro.'],
  ['Perdón y Esperanza', 'José elige perdonar otra vez y confía en el buen plan de Dios para el futuro.'],
] as const;

export const GENESIS_READING_IMAGES: GenesisReadingImage[] = chapterSummaries.map(
  ([title, summary, visualCue], index) => ({
    chapter: index + 1,
    title: {
      en: title,
      es: spanishChapterSummaries[index]?.[0],
    },
    summary: {
      en: summary,
      es: spanishChapterSummaries[index]?.[1],
    },
    visualCue,
    image: GENESIS_READING_IMAGE_SOURCES[index],
  })
);

export function getGenesisReadingImage(chapter: number) {
  return GENESIS_READING_IMAGES.find((entry) => entry.chapter === chapter) ?? null;
}
