import type { ImageSourcePropType } from 'react-native';

export type ShopSticker = {
  key: string;
  name: string;
  image: ImageSourcePropType;
  previewImage?: ImageSourcePropType;
  width: number;
  height: number;
};

export type ShopStickerPack = {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  tag: string;
  priceLabel?: string;
  stickers: ShopSticker[];
  isIncluded?: boolean;
};

export const FLORAL_FAITH_STICKERS: ShopSticker[] = [
  {
    key: 'floral-faith-faith',
    name: 'Faith',
    image: require('../assets/shop/stickers/floral-faith/faith.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/faith.png'),
    width: 732,
    height: 390,
  },
  {
    key: 'floral-faith-hope',
    name: 'Hope',
    image: require('../assets/shop/stickers/floral-faith/hope.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/hope.png'),
    width: 621,
    height: 360,
  },
  {
    key: 'floral-faith-love',
    name: 'Love',
    image: require('../assets/shop/stickers/floral-faith/love.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/love.png'),
    width: 473,
    height: 374,
  },
  {
    key: 'floral-faith-grace',
    name: 'Grace',
    image: require('../assets/shop/stickers/floral-faith/grace.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/grace.png'),
    width: 536,
    height: 386,
  },
  {
    key: 'floral-faith-blessed',
    name: 'Blessed',
    image: require('../assets/shop/stickers/floral-faith/blessed.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/blessed.png'),
    width: 704,
    height: 310,
  },
  {
    key: 'floral-faith-joy',
    name: 'Joy',
    image: require('../assets/shop/stickers/floral-faith/joy.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/joy.png'),
    width: 512,
    height: 380,
  },
  {
    key: 'floral-faith-peace',
    name: 'Peace',
    image: require('../assets/shop/stickers/floral-faith/peace.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/peace.png'),
    width: 553,
    height: 315,
  },
  {
    key: 'floral-faith-mercy',
    name: 'Mercy',
    image: require('../assets/shop/stickers/floral-faith/mercy.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/mercy.png'),
    width: 655,
    height: 370,
  },
  {
    key: 'floral-faith-prayer',
    name: 'Prayer',
    image: require('../assets/shop/stickers/floral-faith/prayer.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/prayer.png'),
    width: 651,
    height: 370,
  },
  {
    key: 'floral-faith-worship',
    name: 'Worship',
    image: require('../assets/shop/stickers/floral-faith/worship.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/worship.png'),
    width: 760,
    height: 361,
  },
  {
    key: 'floral-faith-praise',
    name: 'Praise',
    image: require('../assets/shop/stickers/floral-faith/praise.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/praise.png'),
    width: 606,
    height: 315,
  },
  {
    key: 'floral-faith-glory',
    name: 'Glory',
    image: require('../assets/shop/stickers/floral-faith/glory.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/glory.png'),
    width: 550,
    height: 383,
  },
  {
    key: 'floral-faith-holy',
    name: 'Holy',
    image: require('../assets/shop/stickers/floral-faith/holy.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/holy.png'),
    width: 626,
    height: 368,
  },
  {
    key: 'floral-faith-amen',
    name: 'Amen',
    image: require('../assets/shop/stickers/floral-faith/amen.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/amen.png'),
    width: 516,
    height: 312,
  },
  {
    key: 'floral-faith-hallelujah',
    name: 'Hallelujah',
    image: require('../assets/shop/stickers/floral-faith/hallelujah.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/hallelujah.png'),
    width: 926,
    height: 368,
  },
  {
    key: 'floral-faith-unshaken',
    name: 'Unshaken',
    image: require('../assets/shop/stickers/floral-faith/unshaken.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/unshaken.png'),
    width: 791,
    height: 332,
  },
  {
    key: 'floral-faith-fearless',
    name: 'Fearless',
    image: require('../assets/shop/stickers/floral-faith/fearless.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/fearless.png'),
    width: 725,
    height: 322,
  },
  {
    key: 'floral-faith-bloom',
    name: 'Bloom',
    image: require('../assets/shop/stickers/floral-faith/bloom.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/bloom.png'),
    width: 643,
    height: 310,
  },
  {
    key: 'floral-faith-shine',
    name: 'Shine',
    image: require('../assets/shop/stickers/floral-faith/shine.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/shine.png'),
    width: 595,
    height: 342,
  },
  {
    key: 'floral-faith-gather',
    name: 'Gather',
    image: require('../assets/shop/stickers/floral-faith/gather.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/gather.png'),
    width: 587,
    height: 383,
  },
  {
    key: 'floral-faith-graceful',
    name: 'Graceful',
    image: require('../assets/shop/stickers/floral-faith/graceful.png'),
    previewImage: require('../assets/shop/sticker-previews/floral-faith/graceful.png'),
    width: 697,
    height: 383,
  },
];

export const SCRIPTURE_VERSE_LABEL_STICKERS: ShopSticker[] = [
  {
    key: 'scripture-label-do-everything-in-love',
    name: 'Do Everything in Love',
    image: require('../assets/shop/stickers/scripture-verse-labels/do-everything-in-love.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/do-everything-in-love.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-life-light',
    name: 'Life and Light',
    image: require('../assets/shop/stickers/scripture-verse-labels/life-light.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/life-light.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-rejoice-always',
    name: 'Rejoice Always',
    image: require('../assets/shop/stickers/scripture-verse-labels/rejoice-always.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/rejoice-always.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-do-to-others',
    name: 'Do to Others',
    image: require('../assets/shop/stickers/scripture-verse-labels/do-to-others.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/do-to-others.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-christ-strengthens-me',
    name: 'Christ Strengthens Me',
    image: require('../assets/shop/stickers/scripture-verse-labels/christ-strengthens-me.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/christ-strengthens-me.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-strong-take-heart',
    name: 'Strong and Take Heart',
    image: require('../assets/shop/stickers/scripture-verse-labels/strong-take-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/strong-take-heart.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-give-thanks-circumstances',
    name: 'Give Thanks in All Circumstances',
    image: require('../assets/shop/stickers/scripture-verse-labels/give-thanks-circumstances.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/give-thanks-circumstances.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-minds-above',
    name: 'Set Your Minds Above',
    image: require('../assets/shop/stickers/scripture-verse-labels/minds-above.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/minds-above.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-lord-good-love-endures',
    name: 'His Love Endures Forever',
    image: require('../assets/shop/stickers/scripture-verse-labels/lord-good-love-endures.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/lord-good-love-endures.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-first-loved-us',
    name: 'He First Loved Us',
    image: require('../assets/shop/stickers/scripture-verse-labels/first-loved-us.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/first-loved-us.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-joyful-hope',
    name: 'Joyful in Hope',
    image: require('../assets/shop/stickers/scripture-verse-labels/joyful-hope.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/joyful-hope.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-impossible-for-god',
    name: 'Impossible for God',
    image: require('../assets/shop/stickers/scripture-verse-labels/impossible-for-god.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/impossible-for-god.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-walk-by-faith',
    name: 'Walk by Faith',
    image: require('../assets/shop/stickers/scripture-verse-labels/walk-by-faith.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/walk-by-faith.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-guard-your-heart',
    name: 'Guard Your Heart',
    image: require('../assets/shop/stickers/scripture-verse-labels/guard-your-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/guard-your-heart.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-everything-possible',
    name: 'Everything Is Possible',
    image: require('../assets/shop/stickers/scripture-verse-labels/everything-possible.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/everything-possible.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-lord-shepherd',
    name: 'The Lord Is My Shepherd',
    image: require('../assets/shop/stickers/scripture-verse-labels/lord-shepherd.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/lord-shepherd.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-god-within-her',
    name: 'God Is Within Her',
    image: require('../assets/shop/stickers/scripture-verse-labels/god-within-her.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/god-within-her.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-give-thanks-always',
    name: 'Give Thanks Always',
    image: require('../assets/shop/stickers/scripture-verse-labels/give-thanks-always.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/give-thanks-always.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-pray-without-ceasing',
    name: 'Pray Without Ceasing',
    image: require('../assets/shop/stickers/scripture-verse-labels/pray-without-ceasing.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/pray-without-ceasing.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-look-to-lord',
    name: 'Look to the Lord',
    image: require('../assets/shop/stickers/scripture-verse-labels/look-to-lord.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/look-to-lord.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-hope-in-lord',
    name: 'Hope in the Lord',
    image: require('../assets/shop/stickers/scripture-verse-labels/hope-in-lord.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/hope-in-lord.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-trust-in-you',
    name: 'Trust in You',
    image: require('../assets/shop/stickers/scripture-verse-labels/trust-in-you.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/trust-in-you.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-strength-defense',
    name: 'Strength and Defense',
    image: require('../assets/shop/stickers/scripture-verse-labels/strength-defense.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/strength-defense.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-love-you-lord',
    name: 'I Love You Lord',
    image: require('../assets/shop/stickers/scripture-verse-labels/love-you-lord.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/love-you-lord.png'),
    width: 1050,
    height: 447,
  },
  {
    key: 'scripture-label-delight-yourself',
    name: 'Delight Yourself',
    image: require('../assets/shop/stickers/scripture-verse-labels/delight-yourself.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/delight-yourself.png'),
    width: 902,
    height: 900,
  },
  {
    key: 'scripture-label-spirit-not-fear',
    name: 'Spirit Not of Fear',
    image: require('../assets/shop/stickers/scripture-verse-labels/spirit-not-fear.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/spirit-not-fear.png'),
    width: 902,
    height: 900,
  },
  {
    key: 'scripture-label-strength-shield',
    name: 'Strength and Shield',
    image: require('../assets/shop/stickers/scripture-verse-labels/strength-shield.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/strength-shield.png'),
    width: 902,
    height: 900,
  },
  {
    key: 'scripture-label-brokenhearted',
    name: 'Near to the Brokenhearted',
    image: require('../assets/shop/stickers/scripture-verse-labels/brokenhearted.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/brokenhearted.png'),
    width: 902,
    height: 900,
  },
  {
    key: 'scripture-label-trust-in-lord',
    name: 'Trust in the Lord',
    image: require('../assets/shop/stickers/scripture-verse-labels/trust-in-lord.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/trust-in-lord.png'),
    width: 902,
    height: 900,
  },
  {
    key: 'scripture-label-waters-with-you',
    name: 'Waters With You',
    image: require('../assets/shop/stickers/scripture-verse-labels/waters-with-you.png'),
    previewImage: require('../assets/shop/sticker-previews/scripture-verse-labels/waters-with-you.png'),
    width: 902,
    height: 900,
  },
];

export const FAITH_CANVAS_PASTEL_STICKERS: ShopSticker[] = [
  {
    key: 'faith-canvas-pastels-jesus',
    name: 'Jesus',
    image: require('../assets/shop/stickers/faith-canvas-pastels/jesus.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/jesus.png'),
    width: 620,
    height: 430,
  },
  {
    key: 'faith-canvas-pastels-blessed',
    name: 'Blessed',
    image: require('../assets/shop/stickers/faith-canvas-pastels/blessed.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/blessed.png'),
    width: 660,
    height: 430,
  },
  {
    key: 'faith-canvas-pastels-love',
    name: 'Love',
    image: require('../assets/shop/stickers/faith-canvas-pastels/love.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/love.png'),
    width: 560,
    height: 500,
  },
  {
    key: 'faith-canvas-pastels-faith',
    name: 'Faith',
    image: require('../assets/shop/stickers/faith-canvas-pastels/faith.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/faith.png'),
    width: 620,
    height: 430,
  },
  {
    key: 'faith-canvas-pastels-pastel-cross',
    name: 'Pastel Cross',
    image: require('../assets/shop/stickers/faith-canvas-pastels/pastel-cross.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/pastel-cross.png'),
    width: 620,
    height: 620,
  },
  {
    key: 'faith-canvas-pastels-sunrise-cross',
    name: 'Sunrise Cross',
    image: require('../assets/shop/stickers/faith-canvas-pastels/sunrise-cross.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/sunrise-cross.png'),
    width: 620,
    height: 620,
  },
  {
    key: 'faith-canvas-pastels-open-bible',
    name: 'Bible',
    image: require('../assets/shop/stickers/faith-canvas-pastels/open-bible.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/open-bible.png'),
    width: 780,
    height: 560,
  },
  {
    key: 'faith-canvas-pastels-bible-heart',
    name: 'Bible Heart',
    image: require('../assets/shop/stickers/faith-canvas-pastels/bible-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/bible-heart.png'),
    width: 780,
    height: 560,
  },
  {
    key: 'faith-canvas-pastels-peace-dove',
    name: 'Peace Dove',
    image: require('../assets/shop/stickers/faith-canvas-pastels/peace-dove.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/peace-dove.png'),
    width: 720,
    height: 560,
  },
  {
    key: 'faith-canvas-pastels-dove-branch',
    name: 'Dove Branch',
    image: require('../assets/shop/stickers/faith-canvas-pastels/dove-branch.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/dove-branch.png'),
    width: 720,
    height: 560,
  },
  {
    key: 'faith-canvas-pastels-cross-bouquet',
    name: 'Cross Bouquet',
    image: require('../assets/shop/stickers/faith-canvas-pastels/cross-bouquet.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/cross-bouquet.png'),
    width: 640,
    height: 640,
  },
  {
    key: 'faith-canvas-pastels-canvas-morning',
    name: 'Canvas Morning',
    image: require('../assets/shop/stickers/faith-canvas-pastels/canvas-morning.png'),
    previewImage: require('../assets/shop/sticker-previews/faith-canvas-pastels/canvas-morning.png'),
    width: 760,
    height: 560,
  },
];

export const PRAYER_NIGHT_STICKERS: ShopSticker[] = [
  {
    key: 'prayer-night-prayer-time',
    name: 'Prayer Time',
    image: require('../assets/shop/stickers/prayer-night/prayer-time.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/prayer-time.png'),
    width: 690,
    height: 430,
  },
  {
    key: 'prayer-night-dear-god',
    name: 'Dear God',
    image: require('../assets/shop/stickers/prayer-night/dear-god.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/dear-god.png'),
    width: 620,
    height: 430,
  },
  {
    key: 'prayer-night-amen',
    name: 'Amen',
    image: require('../assets/shop/stickers/prayer-night/amen.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/amen.png'),
    width: 560,
    height: 430,
  },
  {
    key: 'prayer-night-moon-cross',
    name: 'Moon Cross',
    image: require('../assets/shop/stickers/prayer-night/moon-cross.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/moon-cross.png'),
    width: 620,
    height: 620,
  },
  {
    key: 'prayer-night-cloud-heart',
    name: 'Cloud Heart',
    image: require('../assets/shop/stickers/prayer-night/cloud-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/cloud-heart.png'),
    width: 620,
    height: 430,
  },
  {
    key: 'prayer-night-heart-prayer',
    name: 'Heart Prayer',
    image: require('../assets/shop/stickers/prayer-night/heart-prayer.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/heart-prayer.png'),
    width: 620,
    height: 620,
  },
  {
    key: 'prayer-night-prayer-list',
    name: 'Prayer List',
    image: require('../assets/shop/stickers/prayer-night/prayer-list.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/prayer-list.png'),
    width: 700,
    height: 560,
  },
  {
    key: 'prayer-night-answered-prayer',
    name: 'Answered Prayer',
    image: require('../assets/shop/stickers/prayer-night/answered-prayer.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/answered-prayer.png'),
    width: 650,
    height: 430,
  },
  {
    key: 'prayer-night-cozy-bible',
    name: 'Cozy Bible',
    image: require('../assets/shop/stickers/prayer-night/cozy-bible.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/cozy-bible.png'),
    width: 760,
    height: 560,
  },
  {
    key: 'prayer-night-mug-heart',
    name: 'Mug Heart',
    image: require('../assets/shop/stickers/prayer-night/mug-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/mug-heart.png'),
    width: 620,
    height: 560,
  },
  {
    key: 'prayer-night-star-cluster',
    name: 'Star Cluster',
    image: require('../assets/shop/stickers/prayer-night/star-cluster.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/star-cluster.png'),
    width: 620,
    height: 620,
  },
  {
    key: 'prayer-night-sleepy-bow',
    name: 'Sleepy Bow',
    image: require('../assets/shop/stickers/prayer-night/sleepy-bow.png'),
    previewImage: require('../assets/shop/sticker-previews/prayer-night/sleepy-bow.png'),
    width: 600,
    height: 430,
  },
];

export const QUIET_STRENGTH_STICKERS: ShopSticker[] = [
  {
    key: 'quiet-strength-not-alone',
    name: 'Not Alone',
    image: require('../assets/shop/stickers/quiet-strength/not-alone.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/not-alone.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-god-is-near',
    name: 'God Is Near',
    image: require('../assets/shop/stickers/quiet-strength/god-is-near.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/god-is-near.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-be-still',
    name: 'Be Still',
    image: require('../assets/shop/stickers/quiet-strength/be-still.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/be-still.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-keep-going',
    name: 'Keep Going',
    image: require('../assets/shop/stickers/quiet-strength/keep-going.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/keep-going.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-grace-for-today',
    name: 'Grace for Today',
    image: require('../assets/shop/stickers/quiet-strength/grace-for-today.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/grace-for-today.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-steady',
    name: 'Steady',
    image: require('../assets/shop/stickers/quiet-strength/steady.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/steady.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-take-heart',
    name: 'Take Heart',
    image: require('../assets/shop/stickers/quiet-strength/take-heart.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/take-heart.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-deep-breath',
    name: 'Deep Breath',
    image: require('../assets/shop/stickers/quiet-strength/deep-breath.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/deep-breath.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-new-mercies',
    name: 'New Mercies',
    image: require('../assets/shop/stickers/quiet-strength/new-mercies.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/new-mercies.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-rooted',
    name: 'Rooted',
    image: require('../assets/shop/stickers/quiet-strength/rooted.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/rooted.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-held',
    name: 'Held',
    image: require('../assets/shop/stickers/quiet-strength/held.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/held.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'quiet-strength-courage',
    name: 'Courage',
    image: require('../assets/shop/stickers/quiet-strength/courage.png'),
    previewImage: require('../assets/shop/sticker-previews/quiet-strength/courage.png'),
    width: 1254,
    height: 1254,
  },
];

export const PRESSED_FLORALS_STICKERS: ShopSticker[] = [
  {
    key: 'pressed-florals-wildflower-bouquet',
    name: 'Wildflower Bouquet',
    image: require('../assets/shop/stickers/pressed-florals/wildflower-bouquet.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/wildflower-bouquet.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-lavender-sprig',
    name: 'Lavender Sprig',
    image: require('../assets/shop/stickers/pressed-florals/lavender-sprig.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/lavender-sprig.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-olive-blossom',
    name: 'Olive Blossom',
    image: require('../assets/shop/stickers/pressed-florals/olive-blossom.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/olive-blossom.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-chamomile-stems',
    name: 'Chamomile Stems',
    image: require('../assets/shop/stickers/pressed-florals/chamomile-stems.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/chamomile-stems.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-peony-bloom',
    name: 'Peony Bloom',
    image: require('../assets/shop/stickers/pressed-florals/peony-bloom.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/peony-bloom.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'pressed-florals-magnolia-branch',
    name: 'Magnolia Branch',
    image: require('../assets/shop/stickers/pressed-florals/magnolia-branch.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/magnolia-branch.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'pressed-florals-clay-poppy',
    name: 'Clay Poppy',
    image: require('../assets/shop/stickers/pressed-florals/clay-poppy.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/clay-poppy.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-bluebell-cluster',
    name: 'Bluebell Cluster',
    image: require('../assets/shop/stickers/pressed-florals/bluebell-cluster.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/bluebell-cluster.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-fern-wildflower',
    name: 'Fern Wildflower',
    image: require('../assets/shop/stickers/pressed-florals/fern-wildflower.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/fern-wildflower.png'),
    width: 1024,
    height: 1536,
  },
  {
    key: 'pressed-florals-rosehip-branch',
    name: 'Rosehip Branch',
    image: require('../assets/shop/stickers/pressed-florals/rosehip-branch.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/rosehip-branch.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'pressed-florals-daisy-corner',
    name: 'Daisy Corner',
    image: require('../assets/shop/stickers/pressed-florals/daisy-corner.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/daisy-corner.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'pressed-florals-lily-mauve-cluster',
    name: 'Lily Mauve Cluster',
    image: require('../assets/shop/stickers/pressed-florals/lily-mauve-cluster.png'),
    previewImage: require('../assets/shop/sticker-previews/pressed-florals/lily-mauve-cluster.png'),
    width: 1254,
    height: 1254,
  },
];

export const VERSE_MARKERS_STICKERS: ShopSticker[] = [
  {
    key: 'verse-markers-teal-dotted-arrow-tab',
    name: 'Teal Dotted Arrow Tab',
    image: require('../assets/shop/stickers/verse-markers/teal-dotted-arrow-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/teal-dotted-arrow-tab.png'),
    width: 1563,
    height: 1006,
  },
  {
    key: 'verse-markers-coral-dotted-arrow-tab',
    name: 'Coral Dotted Arrow Tab',
    image: require('../assets/shop/stickers/verse-markers/coral-dotted-arrow-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/coral-dotted-arrow-tab.png'),
    width: 1536,
    height: 1024,
  },
  {
    key: 'verse-markers-dusty-blue-dotted-arrow-tab',
    name: 'Dusty Blue Dotted Arrow Tab',
    image: require('../assets/shop/stickers/verse-markers/dusty-blue-dotted-arrow-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/dusty-blue-dotted-arrow-tab.png'),
    width: 1608,
    height: 978,
  },
  {
    key: 'verse-markers-simple-teal-arrow',
    name: 'Simple Teal Arrow',
    image: require('../assets/shop/stickers/verse-markers/simple-teal-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/simple-teal-arrow.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'verse-markers-navy-loop-arrow',
    name: 'Navy Loop Arrow',
    image: require('../assets/shop/stickers/verse-markers/navy-loop-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/navy-loop-arrow.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'verse-markers-triple-down-arrows',
    name: 'Triple Down Arrows',
    image: require('../assets/shop/stickers/verse-markers/triple-down-arrows.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/triple-down-arrows.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'verse-markers-peach-notes-tab',
    name: 'Peach Notes Tab',
    image: require('../assets/shop/stickers/verse-markers/peach-notes-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/peach-notes-tab.png'),
    width: 1254,
    height: 1254,
  },
  {
    key: 'verse-markers-teal-notes-tab',
    name: 'Teal Notes Tab',
    image: require('../assets/shop/stickers/verse-markers/teal-notes-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/teal-notes-tab.png'),
    width: 1530,
    height: 1028,
  },
  {
    key: 'verse-markers-important-arrow-label',
    name: 'Important Arrow Label',
    image: require('../assets/shop/stickers/verse-markers/important-arrow-label.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/important-arrow-label.png'),
    width: 1666,
    height: 944,
  },
  {
    key: 'verse-markers-remember-chevron-label',
    name: 'Remember Chevron Label',
    image: require('../assets/shop/stickers/verse-markers/remember-chevron-label.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/remember-chevron-label.png'),
    width: 1792,
    height: 877,
  },
  {
    key: 'verse-markers-dont-forget-label',
    name: "Don't Forget Label",
    image: require('../assets/shop/stickers/verse-markers/dont-forget-label.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/dont-forget-label.png'),
    width: 1595,
    height: 986,
  },
  {
    key: 'verse-markers-blue-page-tab',
    name: 'Blue Page Tab',
    image: require('../assets/shop/stickers/verse-markers/blue-page-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/verse-markers/blue-page-tab.png'),
    width: 1254,
    height: 1254,
  },
];

export const SOFT_JOURNAL_DECOR_STICKERS: ShopSticker[] = [
  {
    key: 'soft-journal-decor-blush-solid-index-tab',
    name: 'Blush Solid Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/blush-solid-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/blush-solid-index-tab.png'),
    width: 466,
    height: 370,
  },
  {
    key: 'soft-journal-decor-lavender-dot-index-tab',
    name: 'Lavender Dot Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/lavender-dot-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/lavender-dot-index-tab.png'),
    width: 461,
    height: 369,
  },
  {
    key: 'soft-journal-decor-peach-solid-index-tab',
    name: 'Peach Solid Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/peach-solid-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/peach-solid-index-tab.png'),
    width: 460,
    height: 370,
  },
  {
    key: 'soft-journal-decor-mint-dot-index-tab',
    name: 'Mint Dot Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/mint-dot-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/mint-dot-index-tab.png'),
    width: 457,
    height: 369,
  },
  {
    key: 'soft-journal-decor-sky-stripe-index-tab',
    name: 'Sky Stripe Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/sky-stripe-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/sky-stripe-index-tab.png'),
    width: 455,
    height: 371,
  },
  {
    key: 'soft-journal-decor-cream-scallop-index-tab',
    name: 'Cream Scallop Index Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/cream-scallop-index-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/cream-scallop-index-tab.png'),
    width: 459,
    height: 360,
  },
  {
    key: 'soft-journal-decor-blush-dot-washi',
    name: 'Blush Dot Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/blush-dot-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/blush-dot-washi.png'),
    width: 459,
    height: 234,
  },
  {
    key: 'soft-journal-decor-lavender-stripe-washi',
    name: 'Lavender Stripe Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/lavender-stripe-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/lavender-stripe-washi.png'),
    width: 460,
    height: 224,
  },
  {
    key: 'soft-journal-decor-peach-solid-washi',
    name: 'Peach Solid Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/peach-solid-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/peach-solid-washi.png'),
    width: 458,
    height: 228,
  },
  {
    key: 'soft-journal-decor-mint-grid-washi',
    name: 'Mint Grid Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/mint-grid-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/mint-grid-washi.png'),
    width: 461,
    height: 231,
  },
  {
    key: 'soft-journal-decor-sky-diagonal-washi',
    name: 'Sky Diagonal Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/sky-diagonal-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/sky-diagonal-washi.png'),
    width: 463,
    height: 235,
  },
  {
    key: 'soft-journal-decor-cream-solid-washi',
    name: 'Cream Solid Washi',
    image: require('../assets/shop/stickers/soft-journal-decor/cream-solid-washi.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/cream-solid-washi.png'),
    width: 466,
    height: 232,
  },
  {
    key: 'soft-journal-decor-blush-dot-arrow',
    name: 'Blush Dot Arrow',
    image: require('../assets/shop/stickers/soft-journal-decor/blush-dot-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/blush-dot-arrow.png'),
    width: 462,
    height: 326,
  },
  {
    key: 'soft-journal-decor-lavender-curve-arrow',
    name: 'Lavender Curve Arrow',
    image: require('../assets/shop/stickers/soft-journal-decor/lavender-curve-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/lavender-curve-arrow.png'),
    width: 433,
    height: 377,
  },
  {
    key: 'soft-journal-decor-peach-chevron-arrow',
    name: 'Peach Chevron Arrow',
    image: require('../assets/shop/stickers/soft-journal-decor/peach-chevron-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/peach-chevron-arrow.png'),
    width: 373,
    height: 311,
  },
  {
    key: 'soft-journal-decor-mint-ribbon-arrow',
    name: 'Mint Ribbon Arrow',
    image: require('../assets/shop/stickers/soft-journal-decor/mint-ribbon-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/mint-ribbon-arrow.png'),
    width: 518,
    height: 270,
  },
  {
    key: 'soft-journal-decor-sky-down-arrow-cluster',
    name: 'Sky Down Arrow Cluster',
    image: require('../assets/shop/stickers/soft-journal-decor/sky-down-arrow-cluster.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/sky-down-arrow-cluster.png'),
    width: 390,
    height: 380,
  },
  {
    key: 'soft-journal-decor-cream-corner-arrow',
    name: 'Cream Corner Arrow',
    image: require('../assets/shop/stickers/soft-journal-decor/cream-corner-arrow.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/cream-corner-arrow.png'),
    width: 344,
    height: 332,
  },
  {
    key: 'soft-journal-decor-blush-scallop-label',
    name: 'Blush Scallop Label',
    image: require('../assets/shop/stickers/soft-journal-decor/blush-scallop-label.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/blush-scallop-label.png'),
    width: 503,
    height: 500,
  },
  {
    key: 'soft-journal-decor-lavender-rounded-label',
    name: 'Lavender Rounded Label',
    image: require('../assets/shop/stickers/soft-journal-decor/lavender-rounded-label.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/lavender-rounded-label.png'),
    width: 595,
    height: 453,
  },
  {
    key: 'soft-journal-decor-mint-corner-bracket',
    name: 'Mint Corner Bracket',
    image: require('../assets/shop/stickers/soft-journal-decor/mint-corner-bracket.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/mint-corner-bracket.png'),
    width: 391,
    height: 359,
  },
  {
    key: 'soft-journal-decor-peach-flag-tab',
    name: 'Peach Flag Tab',
    image: require('../assets/shop/stickers/soft-journal-decor/peach-flag-tab.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/peach-flag-tab.png'),
    width: 425,
    height: 263,
  },
  {
    key: 'soft-journal-decor-sky-divider-strip',
    name: 'Sky Divider Strip',
    image: require('../assets/shop/stickers/soft-journal-decor/sky-divider-strip.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/sky-divider-strip.png'),
    width: 615,
    height: 191,
  },
  {
    key: 'soft-journal-decor-pastel-dot-cluster',
    name: 'Pastel Dot Cluster',
    image: require('../assets/shop/stickers/soft-journal-decor/pastel-dot-cluster.png'),
    previewImage: require('../assets/shop/sticker-previews/soft-journal-decor/pastel-dot-cluster.png'),
    width: 449,
    height: 213,
  },
];

export const SHOP_STICKER_PACKS: ShopStickerPack[] = [
  {
    id: 'floral-faith-stickers',
    title: 'Floral Faith Stickers',
    subtitle: '21 floral word stickers for decorating verse cards and journal pages',
    category: 'Stickers',
    tag: 'Included',
    stickers: FLORAL_FAITH_STICKERS,
    isIncluded: true,
  },
  {
    id: 'scripture-verse-label-stickers',
    title: 'Scripture Verse Label Stickers',
    subtitle: '30 scripture label stickers for verse cards, Bible notes, and journals',
    category: 'Stickers',
    tag: 'Included',
    stickers: SCRIPTURE_VERSE_LABEL_STICKERS,
    isIncluded: true,
  },
  {
    id: 'faith-canvas-pastel-stickers',
    title: 'Faith Canvas Pastel Stickers',
    subtitle: '12 bold puffy pastel faith stickers made for journal decorating',
    category: 'Stickers',
    tag: 'Included',
    stickers: FAITH_CANVAS_PASTEL_STICKERS,
    isIncluded: true,
  },
  {
    id: 'prayer-night-stickers',
    title: 'Prayer Night Stickers',
    subtitle: '12 cozy pastel prayer stickers for night journals and quiet time',
    category: 'Stickers',
    tag: 'Included',
    stickers: PRAYER_NIGHT_STICKERS,
    isIncluded: true,
  },
  {
    id: 'quiet-strength-stickers',
    title: 'Quiet Strength Stickers',
    subtitle: '12 muted encouragement stickers for teen journals, prayers, and verse art',
    category: 'Stickers',
    tag: '$1',
    priceLabel: '$1',
    stickers: QUIET_STRENGTH_STICKERS,
  },
  {
    id: 'pressed-florals-stickers',
    title: 'Pressed Florals Stickers',
    subtitle: '12 mature botanical stickers for ages 14-16, journals, and verse art',
    category: 'Stickers',
    tag: '$1',
    priceLabel: '$1',
    stickers: PRESSED_FLORALS_STICKERS,
  },
  {
    id: 'verse-markers-stickers',
    title: 'Verse Markers Stickers',
    subtitle: '12 arrow tabs and study labels for decorating favorite verses',
    category: 'Stickers',
    tag: '$1',
    priceLabel: '$1',
    stickers: VERSE_MARKERS_STICKERS,
  },
  {
    id: 'soft-journal-decor-stickers',
    title: 'Soft Journal Decor Stickers',
    subtitle: '24 soft index tabs, washi tape strips, arrows, labels, and decorative pieces',
    category: 'Stickers',
    tag: '$1',
    priceLabel: '$1',
    stickers: SOFT_JOURNAL_DECOR_STICKERS,
  },
];

export const INCLUDED_STICKER_PACKS = SHOP_STICKER_PACKS.filter((pack) => pack.isIncluded);
export const TEST_UNLOCKED_STICKER_PACKS = INCLUDED_STICKER_PACKS;

export const SHOP_STICKERS = [
  ...FLORAL_FAITH_STICKERS,
  ...SCRIPTURE_VERSE_LABEL_STICKERS,
  ...FAITH_CANVAS_PASTEL_STICKERS,
  ...PRAYER_NIGHT_STICKERS,
  ...QUIET_STRENGTH_STICKERS,
  ...PRESSED_FLORALS_STICKERS,
  ...VERSE_MARKERS_STICKERS,
  ...SOFT_JOURNAL_DECOR_STICKERS,
].reduce<Record<string, ShopSticker>>(
  (stickers, sticker) => {
    stickers[sticker.key] = sticker;
    return stickers;
  },
  {
    'faith-floral': FLORAL_FAITH_STICKERS[0],
  }
);

export function getShopSticker(key?: string) {
  if (!key) {
    return null;
  }

  return SHOP_STICKERS[key] ?? null;
}

export function getShopStickerDisplaySize(sticker: ShopSticker, maxSize = 132) {
  const scale = maxSize / Math.max(sticker.width, sticker.height);

  return {
    width: Math.round(sticker.width * scale),
    height: Math.round(sticker.height * scale),
  };
}
